/* The Decision Layer — presenter driven walk through a synthetic agent topology.
 *
 * ILLUSTRATIVE DEMO — synthetic traces. Every number this file renders comes
 * from data/demo_data.js, which is generated by scripts/gen_demo_traces.py and
 * scripts/aggregate.py. Nothing here is measured. There is no measured value
 * anywhere in this repository, so there is no second label to keep straight.
 *
 * Nine beats, advanced with the right arrow, space, or a click, reversed with
 * the left arrow. Every beat is a pure function of the beat number, so going
 * backwards is the same code path as going forwards.
 */

(function () {
  'use strict';

  var GRAPH = window.DEMO_GRAPH;
  var TIMELINE = window.DEMO_TIMELINE;
  var CARDS = window.DEMO_CARDS;
  var TRAJECTORIES = window.DEMO_TRAJECTORIES;

  if (!GRAPH || !TIMELINE || !CARDS || !TRAJECTORIES || !window.d3) {
    document.getElementById('nodata').classList.add('on');
    return;
  }

  // ------------------------------------------------------------------ beats

  var BEATS = [
    { tag: 'Beat 0 — cold open',
      line: 'A customer asks one question.' },
    { tag: 'Beat 1 — the explosion',
      line: 'One question. Forty-seven model calls. This is why “which model” feels unanswerable.' },
    { tag: 'Beat 2 — from one run to the system',
      line: 'Stop evaluating runs. Look at the system.' },
    { tag: 'Beat 3 — the money',
      line: 'Your fifty-call problem is a four-node problem.' },
    { tag: 'Beat 4 — the tax',
      line: 'Part of this heat isn’t work — it’s default settings. This is the shape to go looking for, not a measurement.' },
    { tag: 'Beat 5 — decidable today',
      line: 'The instrument matches the behavior — and we refuse verdicts where we didn’t measure.' },
    { tag: 'Beat 6 — the decision',
      line: 'Three numbers and a contract. That’s what “safe to move” looks like.' },
    { tag: 'Beat 7 — time',
      line: 'One call site at a time. Never big-bang. Watch the bill.' },
    { tag: 'Beat 8 — close',
      line: 'The biggest prize did not clear. That is the contract working, not the contract failing.' },
    { tag: 'Free explore',
      line: 'Hover any call site. Filter by environment or team. Drag the rollout week.' }
  ];

  var LAST_BEAT = BEATS.length - 1;
  var FREE = LAST_BEAT;

  var WIDTH = 1000;
  var HEIGHT = 760;
  var WEEKS = TIMELINE.weeks.length;

  var state = {
    beat: 0,
    week: 1,
    environment: 'all',
    team: 'all',
    selected: null,
    cardOpen: false
  };

  var timers = [];
  var stageScale = 1;

  function clearTimers() {
    timers.forEach(clearTimeout);
    timers = [];
  }

  function later(fn, delay) {
    timers.push(setTimeout(fn, delay));
  }

  // ------------------------------------------------------------- formatting

  var fmtInt = d3.format(',');
  var fmtPct1 = d3.format('.1%');
  var fmtPct0 = d3.format('.0%');
  var fmtUsd0 = d3.format('$,.0f');
  var fmtUsd2 = d3.format('$,.2f');

  function compactCalls(value) {
    if (value >= 1e6) return (value / 1e6).toFixed(2) + ' million';
    if (value >= 1e3) return fmtInt(Math.round(value));
    return fmtInt(value);
  }

  // ------------------------------------------------------------------ model

  var nodes = GRAPH.nodes.map(function (node) { return Object.assign({}, node); });
  var byId = {};
  nodes.forEach(function (node) { byId[node.id] = node; });

  var links = GRAPH.edges.map(function (edge) {
    return { source: edge.source, target: edge.target, frequency: edge.frequency,
             window_count: edge.window_count, per_trajectory: edge.per_trajectory };
  });

  var edgeKey = {};
  links.forEach(function (link) { edgeKey[link.source + '>' + link.target] = link; });

  var radius = d3.scaleSqrt()
    .domain([0, d3.max(nodes, function (n) { return n.calls; })])
    .range([12, 41]);

  nodes.forEach(function (node) { node.r = radius(node.calls); });

  function statusOf(id, week) {
    var row = TIMELINE.timeline[id];
    return row ? row[Math.max(0, Math.min(WEEKS - 1, week - 1))] : 'unmeasured';
  }

  function statusMeta(name) {
    return TIMELINE.statuses[name] || TIMELINE.statuses.unmeasured;
  }

  /* Why each behaviour class is or is not decidable today. This is a claim
     about instruments, not about any result. It is the sentence beat five is
     making, said once per call site rather than shouted across the canvas. */
  var READINESS_REASON = {
    'transform': 'One call in, one call out. A bench can give a verdict here today.',
    'tool decider': 'Tool choice is checkable. What the tool then does to the world is not. Partial.',
    'retrieval': 'The answer depends on what was retrieved, so this needs a trajectory instrument.',
    'orchestration': 'Loops and re-entry. Least spend, most confounds — measure last.'
  };

  var STATUS_COLOR = {
    unmeasured: '#49525f',
    measured: '#6fa8dc',
    shadow: '#8b7fe8',
    canary: '#e8c547',
    migrated: '#35c4a8',
    hold: '#e5534b'
  };

  /* One place computes every derived figure on screen, so the filters and the
     scrubber cannot disagree with each other. Filters sum the environment and
     team grid; the scrubber applies the rollout status's cost multiplier. */
  function view() {
    var week = state.beat < 7 ? 1 : state.week;
    var rows = {};
    var totalCost = 0;
    var totalCalls = 0;
    var baselineCost = 0;

    nodes.forEach(function (node) {
      var calls = 0;
      var baseCost = 0;
      var reasoningTokens = 0;
      var outputTokens = 0;
      node.cells.forEach(function (cell) {
        if (state.environment !== 'all' && cell.environment !== state.environment) return;
        if (state.team !== 'all' && cell.team !== state.team) return;
        calls += cell.calls;
        baseCost += cell.cost_usd;
        reasoningTokens += cell.billed_reasoning_tokens;
        outputTokens += cell.billed_output_tokens;
      });
      var status = statusOf(node.id, week);
      var multiplier = statusMeta(status).cost_multiplier;
      var cost = baseCost * multiplier;
      rows[node.id] = {
        calls: calls,
        baseCost: baseCost,
        cost: cost,
        status: status,
        multiplier: multiplier,
        reasoningShare: outputTokens ? reasoningTokens / outputTokens : 0
      };
      totalCost += cost;
      totalCalls += calls;
      baselineCost += baseCost;
    });

    var ranked = nodes.slice().sort(function (a, b) { return rows[b.id].cost - rows[a.id].cost; });
    var hot = {};
    ranked.slice(0, 4).forEach(function (node) { hot[node.id] = true; });
    var maxCost = ranked.length ? rows[ranked[0].id].cost : 1;

    nodes.forEach(function (node) {
      var row = rows[node.id];
      row.spendShare = totalCost ? row.cost / totalCost : 0;
      row.heat = maxCost ? row.cost / maxCost : 0;
      row.hot = !!hot[node.id];
    });

    return {
      week: week,
      rows: rows,
      ranked: ranked,
      totalCost: totalCost,
      totalCalls: totalCalls,
      baselineCost: baselineCost,
      topFourShare: totalCost
        ? ranked.slice(0, 4).reduce(function (sum, n) { return sum + rows[n.id].cost; }, 0) / totalCost
        : 0
    };
  }

  // ----------------------------------------------------------------- layout

  function layerY(layer) { return 58 + layer * 108; }

  (function computeLayout() {
    var simulation = d3.forceSimulation(nodes)
      .force('x', d3.forceX(WIDTH / 2).strength(0.09))
      .force('y', d3.forceY(function (d) { return layerY(d.layer); }).strength(1.35))
      .force('charge', d3.forceManyBody().strength(-820))
      .force('collide', d3.forceCollide(function (d) { return d.r + 23; }).strength(0.92))
      .force('link', d3.forceLink(links).id(function (d) { return d.id; })
        .distance(120).strength(0.045))
      .stop();

    for (var i = 0; i < 420; i += 1) simulation.tick();

    // The margin has to clear the widest glow halo, not just the widest
    // circle, or the hottest call site bleeds off the side of the stage.
    var margin = d3.max(nodes, function (d) { return d.r; }) + 62;
    nodes.forEach(function (node) {
      node.x = Math.max(margin, Math.min(WIDTH - margin, node.x));
      node.y = layerY(node.layer);
    });
  }());

  function edgePath(link) {
    var s = link.source;
    var t = link.target;
    var sx = s.x;
    var sy = s.y;
    var dx = t.x - s.x;
    var dy = t.y - s.y;
    var distance = Math.sqrt(dx * dx + dy * dy) || 1;
    // Stop short of the target so the arrowhead is not buried under the node.
    var trim = t.r + 10;
    var tx = t.x - (dx / distance) * trim;
    var ty = t.y - (dy / distance) * trim;

    if (t.layer > s.layer) {
      var bend = (ty - sy) * 0.46;
      return 'M' + sx + ',' + sy + ' C' + sx + ',' + (sy + bend) +
             ' ' + tx + ',' + (ty - bend) + ' ' + tx + ',' + ty;
    }
    // A call back up the stack — the orchestrator being re-entered. Arc it
    // wide so a loop reads as a loop rather than as a straight line.
    var side = (sx + tx) / 2 < WIDTH / 2 ? -1 : 1;
    var mx = (sx + tx) / 2 + side * 165;
    var my = (sy + ty) / 2;
    return 'M' + sx + ',' + sy + ' Q' + mx + ',' + my + ' ' + tx + ',' + ty;
  }

  // ------------------------------------------------------------------- draw

  var svg = d3.select('#graph');
  var viewport = d3.select('#viewport');

  svg.select('defs').append('marker')
    .attr('id', 'arrow')
    .attr('viewBox', '0 -4 8 8')
    .attr('refX', 7).attr('refY', 0)
    .attr('markerWidth', 5).attr('markerHeight', 5)
    .attr('orient', 'auto')
    .append('path')
    .attr('d', 'M0,-3.2L7,0L0,3.2')
    .attr('fill', 'currentColor');

  var edgeWidth = d3.scaleSqrt().domain([0, 1]).range([0.7, 6.2]);

  var edgeSel = d3.select('#layer-edges').selectAll('path')
    .data(links)
    .join('path')
    .attr('class', 'edge')
    .attr('d', edgePath)
    .attr('stroke-width', function (d) { return edgeWidth(d.frequency); })
    .attr('marker-end', 'url(#arrow)')
    .style('color', '#2a313c');

  var glowSel = d3.select('#layer-glow').selectAll('circle')
    .data(nodes, function (d) { return d.id; })
    .join('circle')
    .attr('class', 'glow')
    .attr('cx', function (d) { return d.x; })
    .attr('cy', function (d) { return d.y; })
    .attr('fill', 'url(#hot-glow)')
    .attr('r', 0)
    .attr('opacity', 0);

  var nodeSel = d3.select('#layer-nodes').selectAll('g')
    .data(nodes, function (d) { return d.id; })
    .join('g')
    .attr('class', 'node-group')
    .attr('transform', function (d) { return 'translate(' + d.x + ',' + d.y + ')'; });

  nodeSel.append('circle').attr('class', 'status-ring')
    .attr('r', function (d) { return d.r + 7; })
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'class-ring')
    .attr('r', function (d) { return d.r + 3.5; })
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'node-body')
    .attr('r', function (d) { return d.r; })
    .attr('fill', '#20262e')
    .attr('stroke', '#2f3742')
    .attr('stroke-width', 1.2);

  nodeSel.append('circle').attr('class', 'reasoning-band')
    .attr('fill', 'none')
    .attr('stroke', 'url(#reasoning-stripe)')
    .attr('opacity', 0)
    .attr('transform', 'rotate(-90)');

  nodeSel.append('text').attr('class', 'reasoning-text')
    .attr('text-anchor', 'middle')
    .attr('dy', '0.36em')
    .attr('font-size', 11)
    .attr('font-weight', 700)
    .attr('fill', '#1a1206')
    .attr('opacity', 0);

  nodeSel.append('text').attr('class', 'node-label')
    .attr('y', function (d) { return d.r + 17; })
    .text(function (d) { return d.label; });

  nodeSel.append('text').attr('class', 'node-badge')
    .attr('y', function (d) { return d.r + 30; })
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'node-hit')
    .attr('r', function (d) { return d.r + 12; });

  // Behaviour class is drawn as a border treatment, taught at beat five.
  var CLASS_STROKE = {
    'transform': { dash: null, width: 1.6 },
    'tool decider': { dash: '7 5', width: 1.8 },
    'retrieval': { dash: '2 4', width: 2.0 },
    'orchestration': { dash: '14 4 3 4', width: 2.4 }
  };

  // ---------------------------------------------------------------- filters

  function buildChips(containerId, key, values) {
    var container = d3.select(containerId);
    container.selectAll('button')
      .data(values)
      .join('button')
      .attr('class', function (d) { return 'chip' + (state[key] === d.value ? ' active' : ''); })
      .text(function (d) { return d.label; })
      .on('click', function (event, d) {
        state[key] = d.value;
        state.selected = null;
        state.cardOpen = false;
        refreshChips();
        render();
      });
  }

  var ENVIRONMENT_CHOICES = [{ value: 'all', label: 'All' }]
    .concat(GRAPH.meta.environments.map(function (e) {
      return { value: e, label: e.charAt(0).toUpperCase() + e.slice(1) };
    }));

  var TEAM_CHOICES = [{ value: 'all', label: 'All' }]
    .concat(GRAPH.meta.teams.map(function (t) { return { value: t, label: t }; }));

  function refreshChips() {
    buildChips('#filter-environment', 'environment', ENVIRONMENT_CHOICES);
    buildChips('#filter-team', 'team', TEAM_CHOICES);
  }

  refreshChips();

  // --------------------------------------------------------------- scrubber

  var scrubRange = document.getElementById('scrub-range');
  scrubRange.max = String(WEEKS);
  scrubRange.addEventListener('input', function () {
    // A hand on the scrubber wins over the scripted sweep.
    clearTimers();
    state.week = Number(scrubRange.value);
    if (state.beat < 7) state.beat = 7;
    render();
  });

  d3.select('#scrub-ticks').selectAll('span')
    .data(TIMELINE.weeks)
    .join('span')
    .text(function (d) { return 'W' + d.week; });

  // --------------------------------------------------------------- tooltip

  var tooltip = d3.select('#tooltip');

  function showTooltip(event, node) {
    if (state.beat < 2) return;
    var snapshot = view();
    var row = snapshot.rows[node.id];
    var meta = statusMeta(row.status);
    var stage = document.getElementById('stage').getBoundingClientRect();
    var x = (event.clientX - stage.left) / stageScale;
    var y = (event.clientY - stage.top) / stageScale;

    tooltip.html(
      '<div class="tip-name">' + node.label + '</div>' +
      '<div class="tip-class">' + node.behavior_class + ' · ' + node.instrument_readiness + '</div>' +
      '<div class="tip-reason">' + READINESS_REASON[node.behavior_class] + '</div>' +
      '<dl class="tip-grid">' +
      '<dt>Calls, thirty days</dt><dd>' + compactCalls(row.calls) + '</dd>' +
      '<dt>Cost per day</dt><dd>' + fmtUsd2(row.cost / GRAPH.meta.window_days) + '</dd>' +
      '<dt>Share of spend</dt><dd>' + fmtPct1(row.spendShare) + '</dd>' +
      '<dt>Billed reasoning</dt><dd>' + fmtPct0(row.reasoningShare) + '</dd>' +
      '<dt>Blast radius</dt><dd>' + fmtPct0(node.blast_radius) + '</dd>' +
      '</dl>' +
      '<div class="tip-status" style="color:' + STATUS_COLOR[row.status] + '">' +
      meta.label + ' — week ' + snapshot.week + '</div>' +
      (node.has_decision_card
        ? '<div class="tip-hint">Click for the decision card.</div>'
        : '<div class="tip-hint">Unmeasured by design — click to see why.</div>')
    );

    tooltip.classed('on', true)
      .style('left', Math.min(x + 18, 1440 - 250) + 'px')
      .style('top', Math.min(y + 14, 900 - 210) + 'px');
  }

  function hideTooltip() { tooltip.classed('on', false); }

  nodeSel.select('.node-hit')
    .on('mousemove', showTooltip)
    .on('mouseleave', hideTooltip)
    .on('click', function (event, node) {
      if (state.beat < 3) return;
      hideTooltip();
      state.selected = node.id;
      state.cardOpen = true;
      render();
    });

  document.getElementById('card-close').addEventListener('click', function (event) {
    event.stopPropagation();
    state.cardOpen = false;
    render();
  });

  // ------------------------------------------------------------------ panel

  function renderPanel(snapshot) {
    var top = snapshot.ranked.slice(0, 6);
    var restCount = nodes.length - top.length;
    var restShare = 1 - top.reduce(function (sum, n) {
      return sum + snapshot.rows[n.id].spendShare;
    }, 0);

    d3.select('#concentration').html(
      '<div class="conc-big">' + fmtPct0(snapshot.topFourShare) + '</div>' +
      '<div class="conc-text">of spend sits in <b>4 of ' + nodes.length +
      '</b> call sites.<br>' + compactCalls(snapshot.totalCalls) +
      ' model calls · ' + fmtUsd0(snapshot.totalCost) + ' over thirty days.</div>'
    );

    var rows = top.map(function (node) {
      var row = snapshot.rows[node.id];
      return { label: node.label, share: row.spendShare, cost: row.cost, hot: row.hot };
    });
    rows.push({ label: restCount + ' other call sites', share: restShare, cost: null, hot: false });

    var sel = d3.select('#spend-bars').selectAll('div.spend-row').data(rows);
    var enter = sel.enter().append('div').attr('class', 'spend-row');
    enter.append('div').attr('class', 'spend-name');
    enter.append('div').attr('class', 'spend-value');
    enter.append('div').attr('class', 'spend-track').append('div').attr('class', 'spend-fill');
    var merged = enter.merge(sel);
    merged.attr('class', function (d) { return 'spend-row' + (d.hot ? ' is-hot' : ''); });
    merged.select('.spend-name').text(function (d) { return d.label; });
    merged.select('.spend-value').text(function (d) {
      return fmtPct1(d.share) + (d.cost === null ? '' : ' · ' + fmtUsd0(d.cost));
    });
    merged.select('.spend-fill').style('width', function (d) {
      return Math.max(1, d.share * 100 / Math.max(0.0001, rows[0].share)) + '%';
    });
    sel.exit().remove();

    var filterNote = [];
    if (state.environment !== 'all') filterNote.push('environment: ' + state.environment);
    if (state.team !== 'all') filterNote.push('team: ' + state.team);

    d3.select('#panel-sub').text(
      'Thirty day window' + (filterNote.length ? ' · ' + filterNote.join(' · ') : '')
    );

    d3.select('#panel-foot').html(
      'Synthetic traffic, seed ' + GRAPH.meta.seed + '. Spend share is call volume times ' +
      'tokens at a synthetic price book. Nothing here is measured.'
    );
  }

  // ------------------------------------------------------------------- card

  function renderCard(snapshot) {
    var id = state.selected;
    if (!id) return;
    var node = byId[id];
    var card = CARDS.cards[id];
    var row = snapshot.rows[id];
    var status = statusMeta(row.status);
    var gates = CARDS.gates_contract;

    var head =
      '<div class="card-kicker">Decision card</div>' +
      '<h3 class="card-title">' + node.label + '</h3>' +
      '<div class="card-arms">' + CARDS.candidate.label + ' compared against ' +
      CARDS.incumbent.label + '</div>' +
      '<div class="tag-synthetic"><span class="badge-dot"></span>Illustrative — synthetic values</div>';

    /* The rollout row only appears once the scrubber exists. Before beat seven
       there is no week on screen to attach it to, and showing "week one:
       unmeasured" beside a card full of gate results would contradict itself. */
    var rollout = state.beat < 7 ? '' :
      '<div class="verdict-line" style="margin-bottom:14px">' +
      'Rollout status, week ' + snapshot.week + ': ' +
      '<b style="color:' + STATUS_COLOR[row.status] + '">' + status.label + '</b> — ' +
      status.meaning + '</div>';

    if (!card) {
      var blank = CARDS.unmeasured_card;
      d3.select('#card-body').html(
        head +
        '<div class="verdict is-unmeasured">' +
        '<span class="verdict-word">' + blank.verdict + '</span></div>' +
        '<p class="verdict-line">' + blank.verdict_line + '</p>' +
        rollout +
        '<div class="card-why">' + blank.why + '</div>' +
        '<div class="gates-contract"><div class="gates-hash">' +
        '<span>Gates contract</span><code>version ' + gates.version + ' · ' + gates.hash + '</code>' +
        '</div><div class="gates-note">Agreed for the call sites that were measured. This one was not, ' +
        'so no gate was evaluated against it.</div></div>'
      );
      return;
    }

    var metrics = card.headline.map(function (metric) {
      return '<div class="headline-metric">' +
        '<div class="metric-top"><span class="metric-name">' + metric.name + '</span>' +
        '<span class="metric-result ' + metric.result + '">' + metric.result + '</span></div>' +
        '<div class="metric-value">' + metric.value +
        (metric.range ? '<span class="metric-range">' + metric.range + '</span>' : '') + '</div>' +
        (metric.basis ? '<div class="metric-basis">' + metric.basis + '</div>' : '') +
        '</div>';
    }).join('');

    var gateRows = card.gates.map(function (gate) {
      return '<tr><td>' + gate.name + '</td><td>' + gate.observed +
        '</td><td class="' + gate.result + '">' + gate.result + '</td></tr>';
    }).join('');

    d3.select('#card-body').html(
      head +
      '<div class="verdict is-' + card.verdict_tone + '">' +
      '<span class="verdict-word">' + card.verdict + '</span>' +
      '<span class="verdict-gates">' + card.gates_evaluated + ' gates</span></div>' +
      '<p class="verdict-line">' + card.verdict_line + '</p>' +
      rollout +
      metrics +
      '<div class="card-why">' + card.why + '</div>' +
      '<div class="gates-contract">' +
      '<div class="gates-hash"><span>Gates contract</span>' +
      '<code>version ' + gates.version + ' · ' + gates.hash + '</code></div>' +
      '<div class="gates-note">' + gates.note + ' Agreed ' + gates.agreed_on +
      ', before anything was run. The hash is synthetic, like everything else here.</div>' +
      '<table class="gate-table">' + gateRows + '</table>' +
      '</div>' +
      '<div class="card-why" style="border-top:none;padding-top:4px"><b>Next.</b> ' + card.next + '</div>'
    );
  }

  // ------------------------------------------------------------- scoreboard

  function renderScoreboard(snapshot) {
    var counts = { migrated: 0, shadow: 0, hold: 0, other: 0 };
    nodes.forEach(function (node) {
      var status = statusOf(node.id, WEEKS);
      if (status === 'migrated') counts.migrated += 1;
      else if (status === 'shadow') counts.shadow += 1;
      else if (status === 'hold') counts.hold += 1;
      else counts.other += 1;
    });

    var tiles = [
      { key: 'migrated', count: counts.migrated, name: 'Migrated',
        note: 'Gates cleared. Serving the candidate.' },
      { key: 'shadow', count: counts.shadow, name: 'In shadow',
        note: 'Measurement in flight. No verdict yet.' },
      { key: 'hold', count: counts.hold, name: 'Hold',
        note: 'Gates did not clear. Canary rolled back.' },
      { key: 'unmeasured', count: counts.other, name: 'Unmeasured',
        note: TIMELINE.final_scoreboard.note }
    ];

    d3.select('#scoreboard-tiles').selectAll('div.tile')
      .data(tiles)
      .join('div')
      .attr('class', function (d) { return 'tile ' + d.key; })
      .html(function (d) {
        return '<div class="tile-count">' + d.count + '</div>' +
          '<div class="tile-name">' + d.name + '</div>' +
          '<div class="tile-note">' + d.note + '</div>';
      });

    d3.select('#scoreboard-links').html(
      '<a href="data/decision_cards.json">The gates contract</a>' +
      '<a href="https://github.com/catwang42/agent-topology-decision">This repository</a>' +
      '<a href="https://github.com/catwang42/agent-migration-workbench">The measurement workbench</a>' +
      '<a href="data/status_timeline.json">The rollout timeline</a>'
    );
  }

  // ----------------------------------------------------------------- render

  function visuals(beat) {
    return {
      coldOpen: beat === 0,
      counter: beat === 1,
      onlyOrchestrator: beat === 0,
      trajectoryOnly: beat === 1,
      allNodes: beat >= 2,
      heat: beat >= 3,
      panel: beat >= 3 && !(state.cardOpen && beat >= 6),
      filters: beat >= 3,
      reasoning: beat >= 4,
      classRings: beat >= 5,
      badges: beat >= 5,
      scrubber: beat >= 7,
      scoreboard: beat === 8,
      free: beat === FREE
    };
  }

  var revealed = {};   // call sites revealed so far during beat one
  var litEdges = {};

  function render() {
    var beat = state.beat;
    var v = visuals(beat);
    var snapshot = view();

    document.getElementById('coldopen').classList.toggle('on', v.coldOpen);
    document.getElementById('counter').classList.toggle('on', v.counter);
    document.getElementById('filters').classList.toggle('on', v.filters);
    document.getElementById('panel').classList.toggle('on', v.panel);
    document.getElementById('scrubber').classList.toggle('on', v.scrubber);
    document.getElementById('scoreboard').classList.toggle('on', v.scoreboard);
    document.getElementById('card').classList.toggle('on', state.cardOpen && beat >= 6);
    document.getElementById('card').setAttribute('aria-hidden', String(!state.cardOpen));

    // Nodes -----------------------------------------------------------------
    nodeSel.attr('opacity', function (d) {
      if (v.allNodes) {
        if (!v.heat) return 1;
        if (snapshot.rows[d.id].hot) return 1;
        // Once the rollout starts, anything with a status is part of the story
        // and stays legible even if it has cooled out of the top four.
        if (beat >= 7 && snapshot.rows[d.id].status !== 'unmeasured') return 1;
        // The orchestrator comes back up at beat five so its "measure last"
        // badge can be read. Refusing a verdict there is the point of the beat.
        if (v.badges && d.behavior_class === 'orchestration') return 0.62;
        return 0.12;
      }
      if (v.onlyOrchestrator) return d.layer === 0 ? 1 : 0;
      return revealed[d.id] ? 1 : 0.06;
    });

    /* Warm means money still sitting there. A call site that has migrated has
       already moved its money, so it goes cool and teal even though it is
       still one of the larger line items. That colour change is beat seven's
       payoff: the audience should see the heat leave one circle. */
    function warm(d) {
      var row = snapshot.rows[d.id];
      return v.heat && row.hot && row.status !== 'migrated';
    }

    nodeSel.classed('hot', warm);
    nodeSel.classed('migrated', function (d) {
      return v.heat && snapshot.rows[d.id].status === 'migrated';
    });

    nodeSel.select('.node-body')
      .transition().duration(820).ease(d3.easeCubicInOut)
      .attr('fill', function (d) {
        var row = snapshot.rows[d.id];
        if (!v.heat) return '#20262e';
        if (row.status === 'migrated') return '#123830';
        if (!row.hot) return '#1b2027';
        return d3.interpolateRgb('#6b3315', '#ff7a2f')(Math.pow(row.heat, 0.6));
      })
      .attr('stroke', function (d) {
        var row = snapshot.rows[d.id];
        if (!v.heat) return '#2f3742';
        if (row.status === 'migrated') return '#35c4a8';
        return row.hot ? '#ffa76a' : '#232932';
      })
      .attr('stroke-width', function (d) {
        return v.heat && (snapshot.rows[d.id].hot || snapshot.rows[d.id].status === 'migrated')
          ? 1.8 : 1.2;
      });

    glowSel
      .transition().duration(820).ease(d3.easeCubicInOut)
      .attr('r', function (d) {
        var row = snapshot.rows[d.id];
        return warm(d) ? d.r + 26 + row.heat * 34 : 0;
      })
      .attr('opacity', function (d) {
        var row = snapshot.rows[d.id];
        return warm(d) ? 0.35 + row.heat * 0.5 : 0;
      });

    // The reasoning band: an inner striped arc whose sweep is the share of
    // billed output tokens that is reasoning the caller never sees.
    nodeSel.select('.reasoning-band')
      .attr('r', function (d) { return d.r * 0.60; })
      .attr('stroke-width', function (d) { return d.r * 0.40; })
      .attr('stroke-dasharray', function (d) {
        var circumference = 2 * Math.PI * (d.r * 0.60);
        var share = snapshot.rows[d.id].reasoningShare;
        return (circumference * share) + ' ' + circumference;
      })
      .transition().duration(700).ease(d3.easeCubicInOut)
      .attr('opacity', function (d) {
        return v.reasoning && warm(d) ? 1 : 0;
      });

    nodeSel.select('.reasoning-text')
      .text(function (d) { return fmtPct0(snapshot.rows[d.id].reasoningShare); })
      .transition().duration(700)
      .attr('opacity', function (d) {
        return v.reasoning && warm(d) && d.r > 26 ? 0.92 : 0;
      });

    nodeSel.select('.class-ring')
      .attr('stroke', function (d) {
        if (snapshot.rows[d.id].status === 'migrated') return '#7fd9c8';
        return snapshot.rows[d.id].hot ? '#ffb98a' : '#5c6673';
      })
      .attr('stroke-width', function (d) { return CLASS_STROKE[d.behavior_class].width; })
      .attr('stroke-dasharray', function (d) { return CLASS_STROKE[d.behavior_class].dash; })
      .transition().duration(640)
      .attr('opacity', v.classRings ? 0.95 : 0);

    nodeSel.select('.node-badge')
      .attr('fill', function (d) {
        return d.behavior_class === 'orchestration' ? '#8b939e' : '#f0a34a';
      })
      .text(function (d) {
        if (d.behavior_class === 'orchestration') return 'measure last';
        if (d.behavior_class === 'retrieval') return 'trajectory instrument';
        return 'measurable now';
      })
      .transition().duration(640)
      .attr('opacity', function (d) {
        if (!v.badges) return 0;
        return snapshot.rows[d.id].hot || d.behavior_class === 'orchestration' ? 0.95 : 0;
      });

    nodeSel.select('.status-ring')
      .attr('stroke', function (d) { return STATUS_COLOR[snapshot.rows[d.id].status]; })
      .transition().duration(640)
      .attr('opacity', function (d) {
        if (beat < 7) return 0;
        return snapshot.rows[d.id].status === 'unmeasured' ? 0 : 0.95;
      });

    nodeSel.select('.node-label')
      .transition().duration(640)
      .attr('opacity', function (d) {
        if (!v.allNodes) return revealed[d.id] || (v.onlyOrchestrator && d.layer === 0) ? 1 : 0;
        return 1;
      });

    // Edges -----------------------------------------------------------------
    edgeSel
      .transition().duration(760).ease(d3.easeCubicInOut)
      .attr('opacity', function (d) {
        if (!v.allNodes) {
          return litEdges[d.source.id + '>' + d.target.id] ? 0.85 : 0.04;
        }
        if (!v.heat) return 0.42;
        var hot = snapshot.rows[d.source.id].hot && snapshot.rows[d.target.id].hot;
        return hot ? 0.6 : 0.07;
      })
      .attr('stroke', function (d) {
        if (!v.heat) return litEdges[d.source.id + '>' + d.target.id] ? '#ff7a2f' : '#2a313c';
        var hot = snapshot.rows[d.source.id].hot && snapshot.rows[d.target.id].hot;
        return hot ? '#a8532a' : '#232932';
      })
      .style('color', function (d) {
        if (!v.heat) return '#2a313c';
        var hot = snapshot.rows[d.source.id].hot && snapshot.rows[d.target.id].hot;
        return hot ? '#a8532a' : '#232932';
      });

    // Chrome ----------------------------------------------------------------
    if (v.panel) renderPanel(snapshot);
    if (state.cardOpen) renderCard(snapshot);
    if (v.scoreboard) renderScoreboard(snapshot);
    if (v.scrubber) renderScrubber(snapshot);

    scrubRange.value = String(snapshot.week);

    var beatMeta = BEATS[beat];
    d3.select('#caption-beat').text(beatMeta.tag);
    d3.select('#caption-line').text(beatMeta.line);

    d3.select('#footer-provenance').text(
      'synthetic traces · seed ' + GRAPH.meta.seed +
      ' · generated ' + GRAPH.meta.generated_on +
      ' · window ' + GRAPH.meta.window_start + ' to ' + GRAPH.meta.window_end
    );
  }

  function renderScrubber(snapshot) {
    var week = TIMELINE.weeks[snapshot.week - 1];
    d3.select('#scrub-week').text(String(snapshot.week));
    d3.select('#scrub-dates').text(week.start + ' to ' + week.end);

    var perDay = snapshot.totalCost / GRAPH.meta.window_days;
    var basePerDay = snapshot.baselineCost / GRAPH.meta.window_days;
    var delta = basePerDay ? (perDay - basePerDay) / basePerDay : 0;
    var deltaClass = delta < -0.0005 ? 'delta-down' : (delta > 0.0005 ? 'delta-up' : '');
    var arrow = delta < -0.0005 ? '▼ ' : (delta > 0.0005 ? '▲ ' : '');

    /* Week seven to week eight goes the wrong way, because the chunk
       summarizer's canary is withdrawn when its gates do not clear. Against
       week one that still reads as a fall, so say it against last week too —
       otherwise the audience has to hold 18.4 percent in their head to notice
       the number got worse. */
    var stepNote = '';
    if (snapshot.week > 1) {
      var previous = weeklySpendPerDay(snapshot.week - 1);
      if (perDay > previous + 0.5) {
        stepNote = '<span class="delta-up"> · ▲ ' + fmtUsd0(perDay - previous) +
          ' on last week</span>';
      }
    }

    d3.select('#scrub-spend').html(
      'spend <b>' + fmtUsd0(perDay) + '</b> per day ' +
      (deltaClass
        ? '<span class="' + deltaClass + '">' + arrow + fmtPct1(Math.abs(delta)) + '</span> vs week one'
        : '<span style="color:#5b636e">at the week one rate</span>') +
      stepNote
    );
  }

  /* The daily bill at any rollout week, under the filters currently applied.
     Kept separate from view() so the scrubber can look one week back without
     disturbing the state the rest of the page is rendered from. */
  function weeklySpendPerDay(week) {
    var total = 0;
    nodes.forEach(function (node) {
      var baseCost = 0;
      node.cells.forEach(function (cell) {
        if (state.environment !== 'all' && cell.environment !== state.environment) return;
        if (state.team !== 'all' && cell.team !== state.team) return;
        baseCost += cell.cost_usd;
      });
      total += baseCost * statusMeta(statusOf(node.id, week)).cost_multiplier;
    });
    return total / GRAPH.meta.window_days;
  }

  // ------------------------------------------------------- beat animations

  function typeQuestion() {
    var text = GRAPH.meta.opening_question;
    var target = document.getElementById('typed-text');
    target.textContent = '';
    var index = 0;
    function step() {
      if (state.beat !== 0) return;
      target.textContent = text.slice(0, index);
      index += 1;
      if (index <= text.length) later(step, 46);
      else pulseOrchestrator();
    }
    step();
  }

  function pulseOrchestrator() {
    if (state.beat !== 0) return;
    var orchestrator = nodes.filter(function (n) { return n.layer === 0; })[0];
    if (!orchestrator) return;
    var body = nodeSel.filter(function (d) { return d.id === orchestrator.id; }).select('.node-body');
    function beat() {
      if (state.beat !== 0) return;
      body.transition().duration(760).ease(d3.easeCubicOut)
        .attr('stroke', '#ff7a2f').attr('stroke-width', 3.2)
        .transition().duration(760).ease(d3.easeCubicIn)
        .attr('stroke', '#2f3742').attr('stroke-width', 1.2)
        .on('end', function () { later(beat, 120); });
    }
    beat();
  }

  function runTrajectory() {
    var featured = TRAJECTORIES.trajectories.filter(function (t) { return t.featured; })[0]
      || TRAJECTORIES.trajectories[0];
    revealed = {};
    litEdges = {};
    var counterValue = document.getElementById('counter-value');
    counterValue.textContent = '0';

    var calls = featured.calls;
    var bySeq = {};
    calls.forEach(function (call) { bySeq[call.seq] = call; });

    function step(index) {
      if (state.beat !== 1) return;
      if (index >= calls.length) return;
      var call = calls[index];
      revealed[call.call_site] = true;
      if (call.parent_seq !== null && bySeq[call.parent_seq]) {
        var parent = bySeq[call.parent_seq].call_site;
        var key = parent + '>' + call.call_site;
        if (edgeKey[key]) {
          litEdges[key] = true;
          flyAlong(parent, call.call_site);
        }
      }
      counterValue.textContent = String(index + 1);
      paintReveal();
      later(function () { step(index + 1); }, 108);
    }
    step(0);
  }

  /* Beat one fires forty seven times in five seconds. A full render each time
     would restart every transition on the page, so the reveal touches only the
     two things that change: which call sites are lit and which edges are lit. */
  function paintReveal() {
    nodeSel.attr('opacity', function (d) { return revealed[d.id] ? 1 : 0.06; });
    nodeSel.select('.node-label').attr('opacity', function (d) {
      return revealed[d.id] ? 1 : 0;
    });
    edgeSel
      .attr('opacity', function (d) {
        return litEdges[d.source.id + '>' + d.target.id] ? 0.85 : 0.04;
      })
      .attr('stroke', function (d) {
        return litEdges[d.source.id + '>' + d.target.id] ? '#ff7a2f' : '#2a313c';
      });
  }

  function flyAlong(sourceId, targetId) {
    var source = byId[sourceId];
    var target = byId[targetId];
    if (!source || !target) return;
    d3.select('#layer-flyer').append('circle')
      .attr('class', 'flyer')
      .attr('r', 3.6)
      .attr('cx', source.x).attr('cy', source.y)
      .transition().duration(320).ease(d3.easeCubicInOut)
      .attr('cx', target.x).attr('cy', target.y)
      .attr('r', 2.2)
      .style('opacity', 0)
      .remove();
  }

  function completeTrajectory() {
    // Entering beat two from either direction leaves every call site revealed.
    nodes.forEach(function (node) { revealed[node.id] = true; });
    links.forEach(function (link) { litEdges[link.source.id + '>' + link.target.id] = true; });
    document.getElementById('counter-value').textContent =
      String(GRAPH.meta.featured_call_count);
  }

  function runScrubber() {
    state.week = 1;
    render();
    var week = 1;
    function step() {
      if (state.beat !== 7) return;
      week += 1;
      if (week > WEEKS) return;
      state.week = week;
      render();
      later(step, 900);
    }
    later(step, 1100);
  }

  // ------------------------------------------------------------- navigation

  function goTo(beat) {
    beat = Math.max(0, Math.min(FREE, beat));
    var previous = state.beat;
    clearTimers();
    d3.select('#layer-flyer').selectAll('*').remove();
    state.beat = beat;

    if (beat < 7) state.week = 1;
    if (beat === 8) state.week = WEEKS;
    if (beat === FREE && previous === 8) state.week = WEEKS;

    // The decision card opens on the hottest call site at beat six and stays
    // open through the rollout, because the rollout is that card's story.
    if (beat >= 6) {
      if (!state.selected) {
        state.selected = view().ranked[0].id;
        state.cardOpen = true;
      }
    } else {
      state.cardOpen = false;
      state.selected = null;
    }

    if (beat === 0) {
      revealed = {};
      litEdges = {};
      typeQuestion();
    } else if (beat === 1) {
      runTrajectory();
    } else if (beat >= 2) {
      completeTrajectory();
    }

    if (beat === 7) runScrubber();

    // Fade the caption line so a beat change reads as a change.
    var caption = document.getElementById('caption');
    caption.classList.add('swap');
    later(function () { caption.classList.remove('swap'); }, 60);

    updateZoomAvailability();
    render();
  }

  window.addEventListener('keydown', function (event) {
    if (event.key === 'ArrowRight' || event.key === ' ' || event.key === 'PageDown') {
      event.preventDefault();
      goTo(state.beat + 1);
    } else if (event.key === 'ArrowLeft' || event.key === 'PageUp') {
      event.preventDefault();
      goTo(state.beat - 1);
    } else if (event.key === 'Escape') {
      state.cardOpen = false;
      render();
    } else if (event.key === 'Home') {
      goTo(0);
    }
  });

  document.getElementById('stage').addEventListener('click', function (event) {
    // Clicks on the controls drive the controls, not the beat.
    if (event.target.closest('#filters, #card, #scrubber, .node-hit, #scoreboard-links')) return;
    goTo(state.beat + 1);
  });

  // --------------------------------------------------------- free explore

  var zoom = d3.zoom()
    .scaleExtent([0.55, 3.4])
    .on('zoom', function (event) {
      viewport.attr('transform', event.transform);
    });

  // Pan and zoom belong to free explore only. During the beats the camera is
  // the presenter's, not the audience's.
  function updateZoomAvailability() {
    if (state.beat === FREE) {
      svg.call(zoom).on('dblclick.zoom', null);
    } else {
      svg.on('.zoom', null);
      if (viewport.attr('transform')) {
        viewport.transition().duration(640).attr('transform', null);
      }
    }
  }

  // ------------------------------------------------------------------ scale

  function fitStage() {
    var scale = Math.min(window.innerWidth / 1440, window.innerHeight / 900);
    stageScale = Math.min(1, scale);
    document.getElementById('stage').style.transform = 'scale(' + stageScale + ')';
  }

  window.addEventListener('resize', fitStage);
  fitStage();

  goTo(0);
}());
