/* The Decision Layer — presenter driven walk through a synthetic agent topology.
 *
 * ILLUSTRATIVE DEMO — synthetic traces. Every number this file renders comes
 * from data/demo_data.js, which is generated by scripts/gen_demo_traces.py and
 * scripts/aggregate.py. Nothing here is measured. There is no measured value
 * anywhere in this repository, so there is no second label to keep straight.
 *
 * Nine beats plus free explore. Advance with the right arrow, the space bar,
 * the arrow button, a beat dot, or a click anywhere on the canvas; reverse
 * with the left arrow or the back button. Every beat is a pure function of the
 * beat number, so going backwards is the same code path as going forwards.
 *
 * Two renderers share one camera. The graph is drawn with scalable vector
 * graphics because it is a small number of precise glyphs; the traffic flowing
 * along its edges is drawn on a raw canvas underneath, because that is
 * hundreds of moving particles and one draw call per frame beats hundreds of
 * document nodes.
 */

(function () {
  'use strict';

  var GRAPH = window.DEMO_GRAPH;
  var TIMELINE = window.DEMO_TIMELINE;
  var CARDS = window.DEMO_CARDS;
  var TRAJECTORIES = window.DEMO_TRAJECTORIES;

  if (!GRAPH || !TIMELINE || !CARDS || !TRAJECTORIES || !window.d3) {
    document.getElementById('nodata').classList.add('on');
    return;
  }

  // ------------------------------------------------------------------ beats

  var BEATS = [
    { tag: 'Beat 0 — cold open',
      line: 'A customer asks one question.' },
    { tag: 'Beat 1 — the explosion',
      line: 'One question. Forty-seven model calls. This is why “which model” feels unanswerable.' },
    { tag: 'Beat 2 — from one run to the system',
      line: 'Stop evaluating runs. Look at the system.' },
    { tag: 'Beat 3 — the money',
      line: 'Your fifty-call problem is a four-node problem.' },
    { tag: 'Beat 4 — the tax',
      line: 'Part of this heat isn’t work — it’s default settings. This is the shape to go looking for, not a measurement.' },
    { tag: 'Beat 5 — decidable today',
      line: 'The instrument matches the behavior — and we refuse verdicts where we didn’t measure.' },
    { tag: 'Beat 6 — the decision',
      line: 'Three numbers and a contract. That’s what “safe to move” looks like.' },
    { tag: 'Beat 7 — time',
      line: 'One call site at a time. Never big-bang. Watch the bill.' },
    { tag: 'Beat 8 — close',
      line: 'The biggest prize did not clear. That is the contract working, not the contract failing.' },
    { tag: 'Free explore',
      line: 'Hover any call site. Filter by environment or team. Drag the rollout week.' }
  ];

  var LAST_BEAT = BEATS.length - 1;
  var ROLLOUT_BEAT = 7;                      // the eight week rollout, stepped by hand
  var FREE = LAST_BEAT;
  var NUMBERED_BEATS = FREE;                 // beats zero through eight

  /* The canvas band, in stage pixels. These mirror --band-canvas-height in
     style.css; tests/test_layout.py asserts the two agree, so the grid has one
     source of truth even though it is spelled twice. */
  var CANVAS_W = 1440;
  var CANVAS_H = readBandHeight() || 600;
  var FIT_PADDING = 0.06;                    // six percent, per the layout grid
  var PANEL_SPACE = 424;                     // width the spend panel takes back
  var CARD_SPACE = 724;                      // width the decision card takes back
  var QUESTION_SPACE = 104;                  // height the cold open question takes back

  function readBandHeight() {
    if (!window.getComputedStyle) return 0;
    var raw = window.getComputedStyle(document.documentElement)
      .getPropertyValue('--band-canvas-height');
    return parseFloat(raw) || 0;
  }

  var WEEKS = TIMELINE.weeks.length;

  var state = {
    beat: 0,
    week: 1,
    environment: 'all',
    team: 'all',
    selected: null,
    cardOpen: false,
    everAdvanced: false
  };

  var timers = [];
  var stageScale = 1;
  var hoverNode = null;

  /* How long a change takes. A beat is a scene change and gets the full
     easing; a rollout week is one step inside a single scene, and the
     presenter is going to take eight of them in a row, so it gets half. */
  var BEAT_MOTION = { node: 820, ring: 760, mark: 640 };
  var WEEK_MOTION = { node: 500, ring: 500, mark: 420 };
  var motion = BEAT_MOTION;

  var REDUCED = !!(window.matchMedia &&
    window.matchMedia('(prefers-reduced-motion: reduce)').matches);

  function clearTimers() {
    timers.forEach(clearTimeout);
    timers = [];
  }

  function later(fn, delay) {
    timers.push(setTimeout(fn, delay));
  }

  // ------------------------------------------------------------- formatting

  var fmtInt = d3.format(',');
  var fmtPct1 = d3.format('.1%');
  var fmtPct0 = d3.format('.0%');
  var fmtUsd0 = d3.format('$,.0f');
  var fmtUsd2 = d3.format('$,.2f');

  function compactCalls(value) {
    if (value >= 1e6) return (value / 1e6).toFixed(2) + ' million';
    if (value >= 1e3) return fmtInt(Math.round(value));
    return fmtInt(value);
  }

  // ------------------------------------------------------------- the palette

  /* Spend intensity is colour temperature along one ramp. Cyan is the coolest
     thing still running; magenta is where the money is. Nothing in this ramp
     is orange, so the single amber ring that appears at beat seven reads as an
     exception rather than as more of the same. */
  var HEAT_RAMP = d3.scaleLinear()
    .domain([0, 0.5, 1])
    .range(['#22D3EE', '#8B5CF6', '#EC4899'])
    .interpolate(d3.interpolateHcl)
    .clamp(true);

  var CYAN = '#22D3EE';
  var SPACE = '#0A0E17';
  var SURFACE = '#0F1524';
  var DORMANT = '#1E293B';

  // The wires get a floor for the same reason the glyphs do.
  var EDGE_SLATE = '#3D4C66';
  var EDGE_FLOOR = 0.26;

  /* The visibility floor.
   *
   * No call site is ever dimmer than this, at any beat, under any filter: a
   * two pixel cool slate ring, a faint interior, and its name at roughly
   * seventy percent. The ring clears three to one against the background, so
   * it reads from the back of a room rather than only from a chair.
   *
   * This is not decoration. The argument the page makes is that four call
   * sites out of nineteen hold the money, and that argument needs the other
   * fifteen on screen to be an argument at all. Dimming them to nothing
   * turned the claim into a picture of four circles.
   *
   * Heat therefore works as a range above the floor. Beat three's die back
   * takes a cold call site down TO the floor and stops there.
   */
  var FLOOR = {
    stroke: '#B4C4D8',
    strokeOpacity: 0.48,
    strokeWidth: 2,
    fill: '#141D2E',
    label: 0.7
  };

  /* One step above the floor, and the whole system wears it: beats zero, one
     and two, before anybody has been told where the money is. */
  var NEUTRAL = {
    stroke: '#B4C4D8',
    strokeOpacity: 0.72,
    strokeWidth: 2,
    fill: '#18233A',
    label: 0.88
  };

  var STATUS_COLOR = {
    unmeasured: '#334155',
    measured: '#38BDF8',
    shadow: '#8B5CF6',
    canary: '#EC4899',
    migrated: '#10B981',
    hold: '#F59E0B'      // the only amber on the page
  };

  function glowGradient(color) {
    if (color === STATUS_COLOR.migrated) return 'url(#glow-emerald)';
    if (color === STATUS_COLOR.hold) return 'url(#glow-amber)';
    var hue = d3.hsl(color).h;
    if (hue > 240 && hue < 320) return 'url(#glow-violet)';
    if (hue >= 320 || hue < 40) return 'url(#glow-magenta)';
    return 'url(#glow-cyan)';
  }

  function mix(base, accent, amount) {
    return d3.interpolateRgb(base, accent)(amount);
  }

  // ------------------------------------------------------------------ model

  var nodes = GRAPH.nodes.map(function (node) { return Object.assign({}, node); });
  var byId = {};
  nodes.forEach(function (node) { byId[node.id] = node; });

  var links = GRAPH.edges.map(function (edge) {
    return { source: edge.source, target: edge.target, frequency: edge.frequency,
             window_count: edge.window_count, per_trajectory: edge.per_trajectory };
  });

  var edgeKey = {};
  links.forEach(function (link) { edgeKey[link.source + '>' + link.target] = link; });

  /* Call volume, as radius. The floor of the range is set by legibility rather
     than by the data: a ring has to be about thirty pixels across at the fit
     the camera settles on before an audience can see that it is a ring at all,
     and a call site nobody can see is a call site that is not in the argument.
     That costs some dynamic range at the quiet end, which is the cheaper of
     the two losses — colour carries the money, radius only carries volume. */
  var radius = d3.scaleSqrt()
    .domain([0, d3.max(nodes, function (n) { return n.calls; })])
    .range([17, 31]);

  /* Call site names are written out in full, per rule three, and written out
     in full they are wide enough to collide with each other on one line. So
     they wrap onto two balanced lines, and the layout is told how wide each
     one ended up so it can leave room. */
  var CHARACTER_WIDTH = 5.55;   // Inter at 10.5 pixels, near enough for spacing

  function wrapLabel(text) {
    var words = text.split(' ');
    if (words.length < 2 || text.length <= 16) return [text];
    var best = null;
    for (var i = 1; i < words.length; i += 1) {
      var head = words.slice(0, i).join(' ');
      var tail = words.slice(i).join(' ');
      var imbalance = Math.abs(head.length - tail.length);
      if (!best || imbalance < best.imbalance) {
        best = { imbalance: imbalance, lines: [head, tail] };
      }
    }
    return best.lines;
  }

  nodes.forEach(function (node) {
    node.r = radius(node.calls);
    node.labelLines = wrapLabel(node.label);
    node.labelHalfWidth = d3.max(node.labelLines, function (line) {
      return line.length;
    }) * CHARACTER_WIDTH / 2;
  });

  function statusOf(id, week) {
    var row = TIMELINE.timeline[id];
    return row ? row[Math.max(0, Math.min(WEEKS - 1, week - 1))] : 'unmeasured';
  }

  function statusMeta(name) {
    return TIMELINE.statuses[name] || TIMELINE.statuses.unmeasured;
  }

  /* Why each behaviour class is or is not decidable today. This is a claim
     about instruments, not about any result. It is the sentence beat five is
     making, said once per call site rather than shouted across the canvas. */
  var READINESS_REASON = {
    'transform': 'One call in, one call out. A bench can give a verdict here today.',
    'tool decider': 'Tool choice is checkable. What the tool then does to the world is not. Partial.',
    'retrieval': 'The answer depends on what was retrieved, so this needs a trajectory instrument.',
    'orchestration': 'Loops and re-entry. Least spend, most confounds — measure last.'
  };

  // The outer ring says what kind of call site this is, taught at beat five.
  var CLASS_STROKE = {
    'transform': { dash: null, width: 1.5 },
    'tool decider': { dash: '7 5', width: 1.7 },
    'retrieval': { dash: '2 4', width: 1.9 },
    'orchestration': { dash: '14 4 3 4', width: 2.3 }
  };

  /* One place computes every derived figure on screen, so the filters and the
     scrubber cannot disagree with each other. Filters sum the environment and
     team grid; the scrubber applies the rollout status's cost multiplier. */
  function view() {
    var week = state.beat < 7 ? 1 : state.week;
    var rows = {};
    var totalCost = 0;
    var totalCalls = 0;
    var baselineCost = 0;

    nodes.forEach(function (node) {
      var calls = 0;
      var baseCost = 0;
      var reasoningTokens = 0;
      var outputTokens = 0;
      node.cells.forEach(function (cell) {
        if (state.environment !== 'all' && cell.environment !== state.environment) return;
        if (state.team !== 'all' && cell.team !== state.team) return;
        calls += cell.calls;
        baseCost += cell.cost_usd;
        reasoningTokens += cell.billed_reasoning_tokens;
        outputTokens += cell.billed_output_tokens;
      });
      var status = statusOf(node.id, week);
      var multiplier = statusMeta(status).cost_multiplier;
      var cost = baseCost * multiplier;
      rows[node.id] = {
        calls: calls,
        baseCost: baseCost,
        cost: cost,
        status: status,
        multiplier: multiplier,
        reasoningShare: outputTokens ? reasoningTokens / outputTokens : 0
      };
      totalCost += cost;
      totalCalls += calls;
      baselineCost += baseCost;
    });

    var ranked = nodes.slice().sort(function (a, b) { return rows[b.id].cost - rows[a.id].cost; });
    var hot = {};
    ranked.slice(0, 4).forEach(function (node) { hot[node.id] = true; });
    var maxCost = ranked.length ? rows[ranked[0].id].cost : 1;

    nodes.forEach(function (node) {
      var row = rows[node.id];
      row.spendShare = totalCost ? row.cost / totalCost : 0;
      row.heat = maxCost ? row.cost / maxCost : 0;
      row.hot = !!hot[node.id];
    });

    return {
      week: week,
      rows: rows,
      ranked: ranked,
      totalCost: totalCost,
      totalCalls: totalCalls,
      baselineCost: baselineCost,
      topFourShare: totalCost
        ? ranked.slice(0, 4).reduce(function (sum, n) { return sum + rows[n.id].cost; }, 0) / totalCost
        : 0
    };
  }

  // ----------------------------------------------------------------- layout

  /* Seven layers have to fit the canvas band, and the band is what decides
     how large a glyph is on the screen, so this gap is kept tight and the
     room a name needs is bought sideways instead — see the relaxation pass
     at the end of the layout. */
  var LAYER_GAP = 64;

  (function computeLayout() {
    var simulation = d3.forceSimulation(nodes)
      .force('x', d3.forceX(570).strength(0.085))
      .force('y', d3.forceY(function (d) { return d.layer * LAYER_GAP; }).strength(1.4))
      .force('charge', d3.forceManyBody().strength(-700))
      // Wide enough for the glyph and for the name underneath it, whichever
      // of the two needs more room.
      .force('collide', d3.forceCollide(function (d) {
        return Math.max(d.r + 20, d.labelHalfWidth + 11);
      }).strength(0.94))
      .force('link', d3.forceLink(links).id(function (d) { return d.id; })
        .distance(110).strength(0.045))
      .stop();

    for (var i = 0; i < 420; i += 1) simulation.tick();

    // Absolute position does not matter — the camera fits whatever comes out
    // of the simulation into the canvas band. The clamp only stops one stray
    // node from stretching the bounding box and shrinking everything else.
    nodes.forEach(function (node) {
      node.x = Math.max(0, Math.min(1140, node.x));
      node.y = node.layer * LAYER_GAP;
    });

    /* Circles pack, names do not. The simulation keeps the glyphs apart, but
       a name hangs below its glyph and can come to rest on the call site
       underneath it — and a name sitting on a glyph is a glyph the audience
       cannot read. So relax sideways until nothing sits on anything.

       Sideways is the direction with room to spend: the picture is seven
       layers deep and the canvas band is the short dimension, so the camera
       is fitting on height and a wider graph costs nothing until the width
       catches up. */
    for (var pass = 0; pass < 320; pass += 1) {
      var moved = false;
      for (var a = 0; a < nodes.length; a += 1) {
        for (var b = a + 1; b < nodes.length; b += 1) {
          var overlap = worstOverlap(nodes[a], nodes[b]);
          if (overlap <= 0) continue;
          var step = overlap / 2 + 0.4;
          var direction = nodes[a].x <= nodes[b].x ? -1 : 1;
          nodes[a].x += direction * step * 0.55;
          nodes[b].x -= direction * step * 0.55;
          moved = true;
        }
      }
      if (!moved) break;
    }
  }());

  /* The two rectangles a call site occupies: the glyph, and the name under
     it. Both are generous by a couple of pixels, so "just touching" counts as
     touching. */
  function occupancy(d) {
    var half = d.labelHalfWidth + 6;
    var labelTop = d.y + d.r + 11;
    return {
      glyph: { x0: d.x - d.r - 3, x1: d.x + d.r + 3,
               y0: d.y - d.r - 3, y1: d.y + d.r + 3 },
      label: { x0: d.x - half, x1: d.x + half,
               y0: labelTop, y1: labelTop + 6 + d.labelLines.length * 13 }
    };
  }

  // How far apart two call sites have to move before none of their four
  // rectangles touch. Zero when they already clear each other.
  function worstOverlap(one, other) {
    var a = occupancy(one);
    var b = occupancy(other);
    var worst = 0;
    [[a.glyph, b.glyph], [a.glyph, b.label], [a.label, b.glyph], [a.label, b.label]]
      .forEach(function (pair) {
        var wide = Math.min(pair[0].x1, pair[1].x1) - Math.max(pair[0].x0, pair[1].x0);
        var tall = Math.min(pair[0].y1, pair[1].y1) - Math.max(pair[0].y0, pair[1].y0);
        if (wide > 0 && tall > 0 && wide > worst) worst = wide;
      });
    return worst;
  }

  /* How much room a glyph needs around its centre. The camera uses this, so
     the widest halo and the label underneath are inside the frame by
     construction rather than by luck. */
  function extentTop(d)   { return d.r + 46; }
  function extentBottom(d){ return d.r + 46; }
  function extentSide(d)  { return Math.max(d.r + 46, d.labelHalfWidth + 8, 64); }

  // -------------------------------------------------------- edge geometry

  /* One curve, sampled once, used twice: the vector path the browser strokes
     and the polyline the particle system walks. Sampling it here rather than
     asking the document for the path length keeps the two exactly on top of
     each other and keeps the particle loop free of layout reads. */
  var SAMPLES = 34;

  function buildGeometry(link) {
    var s = link.source;
    var t = link.target;
    var dx = t.x - s.x;
    var dy = t.y - s.y;
    var distance = Math.sqrt(dx * dx + dy * dy) || 1;
    var trim = t.r + 9;
    var tx = t.x - (dx / distance) * trim;
    var ty = t.y - (dy / distance) * trim;

    var points = [];
    var d;
    if (t.layer > s.layer) {
      var bend = (ty - s.y) * 0.46;
      var c1 = [s.x, s.y + bend];
      var c2 = [tx, ty - bend];
      d = 'M' + s.x + ',' + s.y + ' C' + c1[0] + ',' + c1[1] +
          ' ' + c2[0] + ',' + c2[1] + ' ' + tx + ',' + ty;
      for (var i = 0; i <= SAMPLES; i += 1) points.push(cubic(s.x, s.y, c1, c2, tx, ty, i / SAMPLES));
    } else {
      // A call back up the stack — the orchestrator being re-entered. Arc it
      // wide so a loop reads as a loop rather than as a straight line.
      var side = (s.x + tx) / 2 < 570 ? -1 : 1;
      var mx = (s.x + tx) / 2 + side * 150;
      var my = (s.y + ty) / 2;
      d = 'M' + s.x + ',' + s.y + ' Q' + mx + ',' + my + ' ' + tx + ',' + ty;
      for (var j = 0; j <= SAMPLES; j += 1) points.push(quad(s.x, s.y, mx, my, tx, ty, j / SAMPLES));
    }

    var cumulative = [0];
    for (var k = 1; k < points.length; k += 1) {
      var ax = points[k][0] - points[k - 1][0];
      var ay = points[k][1] - points[k - 1][1];
      cumulative.push(cumulative[k - 1] + Math.sqrt(ax * ax + ay * ay));
    }
    return { d: d, points: points, cumulative: cumulative,
             length: cumulative[cumulative.length - 1] || 1 };
  }

  function cubic(x0, y0, c1, c2, x3, y3, u) {
    var m = 1 - u;
    var a = m * m * m, b = 3 * m * m * u, c = 3 * m * u * u, e = u * u * u;
    return [a * x0 + b * c1[0] + c * c2[0] + e * x3,
            a * y0 + b * c1[1] + c * c2[1] + e * y3];
  }

  function quad(x0, y0, cx, cy, x2, y2, u) {
    var m = 1 - u;
    return [m * m * x0 + 2 * m * u * cx + u * u * x2,
            m * m * y0 + 2 * m * u * cy + u * u * y2];
  }

  function pointAlong(geometry, u) {
    var target = u * geometry.length;
    var cumulative = geometry.cumulative;
    for (var i = 1; i < cumulative.length; i += 1) {
      if (cumulative[i] >= target) {
        var span = cumulative[i] - cumulative[i - 1] || 1;
        var f = (target - cumulative[i - 1]) / span;
        var a = geometry.points[i - 1];
        var b = geometry.points[i];
        return [a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f];
      }
    }
    return geometry.points[geometry.points.length - 1];
  }

  // ------------------------------------------------------------------- draw

  var svg = d3.select('#graph');
  var viewport = d3.select('#viewport');

  svg.select('defs').append('marker')
    .attr('id', 'arrow')
    .attr('viewBox', '0 -4 8 8')
    .attr('refX', 7).attr('refY', 0)
    .attr('markerWidth', 3.4).attr('markerHeight', 3.4)
    .attr('orient', 'auto')
    .append('path')
    .attr('d', 'M0,-3.2L7,0L0,3.2')
    .attr('fill', 'currentColor');

  links.forEach(function (link) { link.geometry = buildGeometry(link); });

  var edgeWidth = d3.scaleSqrt().domain([0, 1]).range([0.6, 2.6]);

  var edgeSel = d3.select('#layer-edges').selectAll('path')
    .data(links)
    .join('path')
    .attr('class', 'edge')
    .attr('d', function (d) { return d.geometry.d; })
    .attr('stroke-width', function (d) { return edgeWidth(d.frequency); })
    .attr('marker-end', 'url(#arrow)')
    .style('color', DORMANT);

  var glowSel = d3.select('#layer-glow').selectAll('circle')
    .data(nodes, function (d) { return d.id; })
    .join('circle')
    .attr('class', 'glow')
    .attr('cx', function (d) { return d.x; })
    .attr('cy', function (d) { return d.y; })
    .attr('fill', 'url(#glow-cyan)')
    .attr('r', 0)
    .attr('opacity', 0);

  var nodeSel = d3.select('#layer-nodes').selectAll('g')
    .data(nodes, function (d) { return d.id; })
    .join('g')
    .attr('class', 'node-group')
    // The visible name wraps onto two lines, so the whole one is carried here
    // for anything reading the graph rather than looking at it.
    .attr('aria-label', function (d) { return d.label; })
    .attr('transform', function (d) { return 'translate(' + d.x + ',' + d.y + ')'; });

  /* The glyph, from the outside in: an outer ring for behaviour class, a swept
     ring for spend share, the body, and a glowing core whose size is the share
     of billed output that is reasoning the caller never sees. The rollout
     status rides as a small dot in orbit. */

  nodeSel.append('circle').attr('class', 'class-ring')
    .attr('r', function (d) { return d.r + 9; })
    .attr('fill', 'none')
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'spend-arc')
    .attr('r', function (d) { return d.r + 4; })
    .attr('fill', 'none')
    .attr('stroke-width', 2.6)
    .attr('transform', 'rotate(-90)')
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'node-body')
    .attr('r', function (d) { return d.r; })
    .attr('fill', SURFACE)
    .attr('stroke', DORMANT)
    .attr('stroke-width', 1.2);

  nodeSel.append('circle').attr('class', 'core-bloom')
    .attr('r', 0)
    .attr('fill', 'url(#glow-cyan)')
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'core')
    .attr('r', 0)
    .attr('opacity', 0);

  nodeSel.append('text').attr('class', 'core-text')
    .attr('dy', '0.35em')
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'status-dot')
    .attr('r', 4.2)
    .attr('cx', function (d) { return Math.cos(0.61) * (d.r + 13); })
    .attr('cy', function (d) { return Math.sin(0.61) * (d.r + 13); })
    .attr('stroke', SPACE)
    .attr('stroke-width', 1.6)
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'hover-ring')
    .attr('r', function (d) { return d.r + 13; });

  nodeSel.append('text').attr('class', 'node-label')
    .attr('y', function (d) { return d.r + 21; })
    .selectAll('tspan')
    .data(function (d) {
      return d.labelLines.map(function (line, index) {
        return { line: line, index: index };
      });
    })
    .join('tspan')
    .attr('x', 0)
    .attr('dy', function (d) { return d.index === 0 ? 0 : 11; })
    .text(function (d) { return d.line; });

  nodeSel.append('text').attr('class', 'node-badge')
    .attr('y', function (d) { return d.r + 21 + d.labelLines.length * 11; })
    .attr('opacity', 0);

  nodeSel.append('circle').attr('class', 'node-hit')
    .attr('r', function (d) { return d.r + 13; });

  // ----------------------------------------------------------- the camera

  /* One camera drives both renderers. It refits on every beat transition and
     whenever an overlay opens, so the graph is always centred in whatever
     rectangle is actually free — which is how the composition stays inside
     its band instead of spilling over the caption. */

  var camera = { x: 0, y: 0, k: 1 };

  /* How much of the canvas an overlay has taken, so the camera can frame the
     graph in what is left rather than letting the two fight for the pixels. */
  function overlaySpace() {
    if (state.cardOpen && state.beat >= 6) return CARD_SPACE;
    return visuals(state.beat).panel ? PANEL_SPACE : 0;
  }

  function boundsOf(subset) {
    var x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    subset.forEach(function (d) {
      x0 = Math.min(x0, d.x - extentSide(d));
      x1 = Math.max(x1, d.x + extentSide(d));
      y0 = Math.min(y0, d.y - extentTop(d));
      y1 = Math.max(y1, d.y + extentBottom(d));
    });
    return { x: x0, y: y0, w: Math.max(1, x1 - x0), h: Math.max(1, y1 - y0) };
  }

  function targetCamera() {
    /* Every call site is on screen at every beat, so the camera frames the
       whole system at every beat too. The cold open is an exception to the
       framing, not to the content: the question needs the top of the band, so
       the system is fitted into what is left underneath it and the audience
       sees the shape of the thing before the first word of the story. */
    var bounds = boundsOf(nodes);
    var width = CANVAS_W - overlaySpace();
    var top = state.beat === 0 ? QUESTION_SPACE : 0;
    var height = CANVAS_H - top;
    var k = Math.min(
      width * (1 - 2 * FIT_PADDING) / bounds.w,
      height * (1 - 2 * FIT_PADDING) / bounds.h,
      1.6
    );
    return {
      k: k,
      x: width / 2 - k * (bounds.x + bounds.w / 2),
      y: top + height / 2 - k * (bounds.y + bounds.h / 2)
    };
  }

  function applyCamera(next) {
    camera = next;
    viewport.attr('transform',
      'translate(' + camera.x + ',' + camera.y + ') scale(' + camera.k + ')');
  }

  function fitCamera(animate) {
    var next = targetCamera();
    if (!animate || REDUCED) { applyCamera(next); return; }
    var from = { x: camera.x, y: camera.y, k: camera.k };
    svg.transition('camera').duration(760).ease(d3.easeCubicInOut)
      .tween('camera', function () {
        var interpolate = d3.interpolateObject(from, next);
        return function (t) { applyCamera(interpolate(t)); };
      });
  }

  applyCamera(targetCamera());

  // ------------------------------------------------------ particle system

  /* Directed traffic, drawn as light. Speed follows how often an edge is
     walked, density follows how much volume it carries, and colour follows the
     same heat ramp the nodes use, so the flow and the glyphs are telling one
     story. Everything here is synthetic, like every other number on the page. */

  var canvas = document.getElementById('particles');
  var DPR = Math.min(2, window.devicePixelRatio || 1);
  var ctx = null;
  try {
    ctx = canvas && canvas.getContext ? canvas.getContext('2d') : null;
  } catch (error) {
    ctx = null;              // a document with no canvas support; the page still works
  }

  if (canvas) {
    canvas.width = Math.round(CANVAS_W * DPR);
    canvas.height = Math.round(CANVAS_H * DPR);
  }

  var flow = links.map(function (link) {
    var count = Math.max(3, Math.round(3 + link.frequency * 16));
    var particles = [];
    for (var i = 0; i < count; i += 1) {
      particles.push({
        u: (i + 0.37 * (i % 3)) / count,     // spread without a random source
        size: 1.5 + link.frequency * 1.7
      });
    }
    return {
      link: link,
      particles: particles,
      pixelsPerSecond: 34 + link.frequency * 120,
      // Eased towards their targets each frame so a beat change is a fade,
      // not a jump.
      alpha: 0, targetAlpha: 0,
      density: 0.8, targetDensity: 0.8,
      speedScale: 1, targetSpeedScale: 1,
      color: CYAN, targetColor: CYAN
    };
  });

  var flowByKey = {};
  flow.forEach(function (f) { flowByKey[f.link.source.id + '>' + f.link.target.id] = f; });

  var pulses = [];          // beat one: the single trajectory racing the counter

  var spriteCache = {};

  function sprite(color) {
    if (spriteCache[color]) return spriteCache[color];
    var size = 34;
    var offscreen = document.createElement('canvas');
    offscreen.width = size;
    offscreen.height = size;
    var g = null;
    try { g = offscreen.getContext ? offscreen.getContext('2d') : null; } catch (e) { g = null; }
    if (!g || !g.createRadialGradient) return null;
    var rgb = d3.rgb(color);
    var body = rgb.r + ',' + rgb.g + ',' + rgb.b;
    var gradient = g.createRadialGradient(size / 2, size / 2, 0, size / 2, size / 2, size / 2);
    gradient.addColorStop(0, 'rgba(255,255,255,0.92)');
    gradient.addColorStop(0.2, 'rgba(' + body + ',0.95)');
    gradient.addColorStop(0.5, 'rgba(' + body + ',0.3)');
    gradient.addColorStop(1, 'rgba(' + body + ',0)');
    g.fillStyle = gradient;
    g.fillRect(0, 0, size, size);
    spriteCache[color] = offscreen;
    return offscreen;
  }

  /* What the traffic should look like at this beat, under these filters, at
     this rollout week. Called once per render, never per frame. */
  function updateFlow(snapshot, v) {
    flow.forEach(function (f) {
      var sourceRow = snapshot.rows[f.link.source.id];
      var targetRow = snapshot.rows[f.link.target.id];
      var live = sourceRow.hot && targetRow.hot;
      var heat = Math.max(sourceRow.heat, targetRow.heat);
      var statuses = [sourceRow.status, targetRow.status];

      if (!v.flow) {
        f.targetAlpha = 0;
        return;
      }
      if (!v.heat) {
        // Beat two: the whole system running, before anyone has been told
        // where the money is.
        f.targetAlpha = 0.8;
        f.targetColor = CYAN;
        f.targetDensity = 0.8;
        f.targetSpeedScale = 1;
        return;
      }

      f.targetColor = HEAT_RAMP(heat);
      f.targetAlpha = live ? 0.95 : 0.05;
      f.targetDensity = 0.8;
      f.targetSpeedScale = 1;

      // Beat seven. A call site that has migrated is running the cheaper model,
      // so its traffic goes emerald and visibly thins out. A call site on hold
      // keeps its dense flow and picks up the amber of the exception.
      if (statuses.indexOf('migrated') >= 0) {
        f.targetColor = STATUS_COLOR.migrated;
        f.targetAlpha = Math.max(f.targetAlpha, 0.5);
        f.targetDensity = 0.32;
        f.targetSpeedScale = 0.7;
      } else if (statuses.indexOf('hold') >= 0) {
        f.targetColor = mix(HEAT_RAMP(heat), STATUS_COLOR.hold, 0.42);
        f.targetAlpha = 1;
        f.targetDensity = 1;
        f.targetSpeedScale = 1.15;
      }
    });
  }

  function stepFlow(dt) {
    var ease = Math.min(1, dt * 3.4);
    for (var i = 0; i < flow.length; i += 1) {
      var f = flow[i];
      f.alpha += (f.targetAlpha - f.alpha) * ease;
      f.density += (f.targetDensity - f.density) * ease;
      f.speedScale += (f.targetSpeedScale - f.speedScale) * ease;
      if (f.color !== f.targetColor) f.color = f.targetColor;

      if (f.alpha < 0.005) continue;
      var boost = (hoverNode &&
        (hoverNode === f.link.source.id || hoverNode === f.link.target.id)) ? 2.4 : 1;
      var step = (f.pixelsPerSecond * f.speedScale * boost * dt) / f.link.geometry.length;
      for (var p = 0; p < f.particles.length; p += 1) {
        f.particles[p].u = (f.particles[p].u + step) % 1;
      }
    }

    for (var q = pulses.length - 1; q >= 0; q -= 1) {
      var pulse = pulses[q];
      pulse.u += dt / pulse.duration;
      if (pulse.u >= 1) pulses.splice(q, 1);
    }
  }

  function drawFlow() {
    if (!ctx) return;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.setTransform(camera.k * DPR, 0, 0, camera.k * DPR, camera.x * DPR, camera.y * DPR);
    ctx.globalCompositeOperation = 'lighter';

    for (var i = 0; i < flow.length; i += 1) {
      var f = flow[i];
      if (f.alpha < 0.02) continue;
      var image = sprite(f.color);
      if (!image) continue;
      var shown = Math.max(1, Math.ceil(f.particles.length * f.density));
      ctx.globalAlpha = f.alpha;
      for (var p = 0; p < shown; p += 1) {
        var particle = f.particles[p];
        var at = pointAlong(f.link.geometry, particle.u);
        var halo = particle.size * 2.7;
        ctx.drawImage(image, at[0] - halo, at[1] - halo, halo * 2, halo * 2);
      }
    }

    for (var q = 0; q < pulses.length; q += 1) {
      var pulse = pulses[q];
      var head = sprite('#A5F3FC');
      if (!head) break;
      var point = pointAlong(pulse.geometry, Math.min(1, pulse.u));
      var size = 13 * (1 - 0.45 * pulse.u);
      ctx.globalAlpha = 1 - pulse.u * 0.6;
      ctx.drawImage(head, point[0] - size, point[1] - size, size * 2, size * 2);
    }

    ctx.globalAlpha = 1;
    ctx.globalCompositeOperation = 'source-over';
  }

  var lastFrame = 0;

  function frame(now) {
    if (!REDUCED) window.requestAnimationFrame(frame);
    var dt = lastFrame ? Math.min(0.05, (now - lastFrame) / 1000) : 0.016;
    lastFrame = now;
    stepFlow(dt);
    drawFlow();
  }

  if (ctx && window.requestAnimationFrame) {
    if (REDUCED) {
      // Still show where the traffic is, just hold it still.
      stepFlow(1);
      drawFlow();
    } else {
      window.requestAnimationFrame(frame);
    }
  }

  // ---------------------------------------------------------------- filters

  function buildChips(containerId, key, values) {
    var container = d3.select(containerId);
    container.selectAll('button')
      .data(values)
      .join('button')
      .attr('class', function (d) { return 'chip' + (state[key] === d.value ? ' active' : ''); })
      .text(function (d) { return d.label; })
      .on('click', function (event, d) {
        event.stopPropagation();
        state[key] = d.value;
        state.selected = null;
        state.cardOpen = false;
        refreshChips();
        render();
      });
  }

  var ENVIRONMENT_CHOICES = [{ value: 'all', label: 'All' }]
    .concat(GRAPH.meta.environments.map(function (e) {
      return { value: e, label: e.charAt(0).toUpperCase() + e.slice(1) };
    }));

  var TEAM_CHOICES = [{ value: 'all', label: 'All' }]
    .concat(GRAPH.meta.teams.map(function (t) { return { value: t, label: t }; }));

  function refreshChips() {
    buildChips('#filter-environment', 'environment', ENVIRONMENT_CHOICES);
    buildChips('#filter-team', 'team', TEAM_CHOICES);
  }

  refreshChips();

  // --------------------------------------------------------------- scrubber

  var scrubRange = document.getElementById('scrub-range');
  scrubRange.max = String(WEEKS);
  scrubRange.addEventListener('input', function () {
    // Dragging and stepping are one control with two handles. Both land here,
    // so the pill, the week marker and the graph cannot disagree about which
    // week is on screen.
    goToWeek(Number(scrubRange.value));
  });

  // --------------------------------------------------------------- tooltip

  var tooltip = d3.select('#tooltip');

  function showTooltip(event, node) {
    if (state.beat < 2) return;
    var snapshot = view();
    var row = snapshot.rows[node.id];
    var meta = statusMeta(row.status);
    var stage = document.getElementById('stage').getBoundingClientRect();
    var x = (event.clientX - stage.left) / stageScale;
    var y = (event.clientY - stage.top) / stageScale;

    tooltip.html(
      '<div class="tip-name">' + node.label + '</div>' +
      '<div class="tip-class">' + node.behavior_class + ' · ' + node.instrument_readiness + '</div>' +
      '<div class="tip-reason">' + READINESS_REASON[node.behavior_class] + '</div>' +
      '<dl class="tip-grid">' +
      '<dt>Calls, thirty days</dt><dd>' + compactCalls(row.calls) + '</dd>' +
      '<dt>Cost per day</dt><dd>' + fmtUsd2(row.cost / GRAPH.meta.window_days) + '</dd>' +
      '<dt>Share of spend</dt><dd>' + fmtPct1(row.spendShare) + '</dd>' +
      '<dt>Billed reasoning</dt><dd>' + fmtPct0(row.reasoningShare) + '</dd>' +
      '<dt>Blast radius</dt><dd>' + fmtPct0(node.blast_radius) + '</dd>' +
      '</dl>' +
      '<div class="tip-status" style="color:' + STATUS_COLOR[row.status] + '">' +
      meta.label + ' — week ' + snapshot.week + '</div>' +
      (node.has_decision_card
        ? '<div class="tip-hint">Click for the decision card.</div>'
        : '<div class="tip-hint">Unmeasured by design — click to see why.</div>')
    );

    tooltip.classed('on', true)
      .style('left', Math.min(x + 18, 1440 - 262) + 'px')
      .style('top', Math.min(y + 14, 900 - 240) + 'px');
  }

  function hideTooltip() { tooltip.classed('on', false); }

  nodeSel.select('.node-hit')
    .on('mousemove', showTooltip)
    .on('mouseenter', function (event, node) { hoverNode = node.id; })
    .on('mouseleave', function () { hoverNode = null; hideTooltip(); })
    .on('click', function (event, node) {
      event.stopPropagation();
      if (state.beat < 3) return;
      hideTooltip();
      state.selected = node.id;
      state.cardOpen = true;
      render();
    });

  document.getElementById('card-close').addEventListener('click', function (event) {
    event.stopPropagation();
    state.cardOpen = false;
    render();
  });

  // ------------------------------------------------------------------ panel

  function renderPanel(snapshot) {
    var top = snapshot.ranked.slice(0, 6);
    var restCount = nodes.length - top.length;
    var restShare = 1 - top.reduce(function (sum, n) {
      return sum + snapshot.rows[n.id].spendShare;
    }, 0);

    d3.select('#concentration').html(
      '<div class="conc-big">' + fmtPct0(snapshot.topFourShare) + '</div>' +
      '<div class="conc-text">of spend sits in <b>4 of ' + nodes.length +
      '</b> call sites.<br>' + compactCalls(snapshot.totalCalls) +
      ' model calls · ' + fmtUsd0(snapshot.totalCost) + ' over thirty days.</div>'
    );

    var rows = top.map(function (node) {
      var row = snapshot.rows[node.id];
      return { label: node.label, share: row.spendShare, cost: row.cost,
               hot: row.hot, heat: row.heat, status: row.status };
    });
    rows.push({ label: restCount + ' other call sites', share: restShare, cost: null,
                hot: false, heat: 0, status: 'unmeasured' });

    var sel = d3.select('#spend-bars').selectAll('div.spend-row').data(rows);
    var enter = sel.enter().append('div').attr('class', 'spend-row');
    enter.append('div').attr('class', 'spend-name');
    enter.append('div').attr('class', 'spend-value');
    enter.append('div').attr('class', 'spend-track').append('div').attr('class', 'spend-fill');
    var merged = enter.merge(sel);
    merged.attr('class', function (d) { return 'spend-row' + (d.hot ? ' is-hot' : ''); });
    merged.select('.spend-name').text(function (d) { return d.label; });
    merged.select('.spend-value').text(function (d) {
      return fmtPct1(d.share) + (d.cost === null ? '' : ' · ' + fmtUsd0(d.cost));
    });
    merged.select('.spend-fill')
      .style('width', function (d) {
        return Math.max(1, d.share * 100 / Math.max(0.0001, rows[0].share)) + '%';
      })
      .style('background', function (d) {
        if (d.status === 'migrated') return STATUS_COLOR.migrated;
        return d.hot ? HEAT_RAMP(d.heat) : DORMANT;
      });
    sel.exit().remove();

    var filterNote = [];
    if (state.environment !== 'all') filterNote.push('environment: ' + state.environment);
    if (state.team !== 'all') filterNote.push('team: ' + state.team);

    d3.select('#panel-sub').text(
      'Thirty day window' + (filterNote.length ? ' · ' + filterNote.join(' · ') : '')
    );

    d3.select('#panel-foot').html(
      'Synthetic traffic, seed ' + GRAPH.meta.seed + '. Spend share is call volume times ' +
      'tokens at a synthetic price book. Nothing here is measured.'
    );
  }

  // ------------------------------------------------------------------- card

  function renderCard(snapshot) {
    var id = state.selected;
    if (!id) return;
    var node = byId[id];
    var card = CARDS.cards[id];
    var row = snapshot.rows[id];
    var status = statusMeta(row.status);
    var gates = CARDS.gates_contract;

    var head =
      '<div class="card-kicker">Decision card</div>' +
      '<h3 class="card-title">' + node.label + '</h3>' +
      '<div class="card-provenance">' +
      '<div class="card-arms">' + CARDS.candidate.label + ' compared against ' +
      CARDS.incumbent.label + '</div>' +
      '<div class="tag-synthetic"><span class="badge-dot"></span>Illustrative — synthetic values</div>' +
      '</div>';

    /* The rollout row only appears once the scrubber exists. Before beat seven
       there is no week on screen to attach it to, and showing "week one:
       unmeasured" beside a card full of gate results would contradict itself. */
    var rollout = state.beat < 7 ? '' :
      '<div class="verdict-line" style="margin-bottom:14px">' +
      'Rollout status, week ' + snapshot.week + ': ' +
      '<b style="color:' + STATUS_COLOR[row.status] + '">' + status.label + '</b> — ' +
      status.meaning + '</div>';

    if (!card) {
      var blank = CARDS.unmeasured_card;
      d3.select('#card-body').html(
        head +
        '<div class="card-columns"><div class="card-column">' +
        '<div class="verdict is-unmeasured">' +
        '<span class="verdict-word">' + blank.verdict + '</span></div>' +
        '<p class="verdict-line">' + blank.verdict_line + '</p>' +
        rollout +
        '</div><div class="card-column">' +
        '<div class="card-why">' + blank.why + '</div>' +
        '<div class="gates-contract"><div class="gates-hash">' +
        '<span>Gates contract</span><code>version ' + gates.version + ' · ' + gates.hash + '</code>' +
        '</div><div class="gates-note">Agreed for the call sites that were measured. This one was not, ' +
        'so no gate was evaluated against it.</div></div>' +
        '</div></div>'
      );
      return;
    }

    var metrics = card.headline.map(function (metric) {
      return '<div class="headline-metric">' +
        '<div class="metric-top"><span class="metric-name">' + metric.name + '</span>' +
        '<span class="metric-result ' + metric.result + '">' + metric.result + '</span></div>' +
        '<div class="metric-value">' + metric.value +
        (metric.range ? '<span class="metric-range">' + metric.range + '</span>' : '') + '</div>' +
        (metric.basis ? '<div class="metric-basis">' + metric.basis + '</div>' : '') +
        '</div>';
    }).join('');

    var gateRows = card.gates.map(function (gate) {
      return '<tr><td>' + gate.name + '</td><td>' + gate.observed +
        '</td><td class="' + gate.result + '">' + gate.result + '</td></tr>';
    }).join('');

    /* Two columns. The verdict and what it rests on go on the left, the reason
       and the contract it was judged against go on the right, and the whole
       card fits the canvas band without a scroll — a card the audience has to
       scroll is a card whose last line nobody reads. */
    d3.select('#card-body').html(
      head +
      '<div class="card-columns"><div class="card-column">' +
      '<div class="verdict is-' + card.verdict_tone + '">' +
      '<span class="verdict-word">' + card.verdict + '</span>' +
      '<span class="verdict-gates">' + card.gates_evaluated + ' gates</span></div>' +
      '<p class="verdict-line">' + card.verdict_line + '</p>' +
      rollout +
      metrics +
      '</div><div class="card-column">' +
      '<div class="card-why">' + card.why + '</div>' +
      '<div class="gates-contract">' +
      '<div class="gates-hash"><span>Gates contract</span>' +
      '<code>version ' + gates.version + ' · ' + gates.hash + '</code></div>' +
      '<div class="gates-note">' + gates.note + ' Agreed ' + gates.agreed_on + '.</div>' +
      '<table class="gate-table">' + gateRows + '</table>' +
      '</div>' +
      '<div class="card-why"><b>Next.</b> ' + card.next + '</div>' +
      '</div></div>'
    );
  }

  // ------------------------------------------------------------- scoreboard

  function renderScoreboard() {
    var counts = { migrated: 0, shadow: 0, hold: 0, other: 0 };
    nodes.forEach(function (node) {
      var status = statusOf(node.id, WEEKS);
      if (status === 'migrated') counts.migrated += 1;
      else if (status === 'shadow') counts.shadow += 1;
      else if (status === 'hold') counts.hold += 1;
      else counts.other += 1;
    });

    var tiles = [
      { key: 'migrated', count: counts.migrated, name: 'Migrated',
        note: 'Gates cleared. Serving the candidate.' },
      { key: 'shadow', count: counts.shadow, name: 'In shadow',
        note: 'Measurement in flight. No verdict yet.' },
      { key: 'hold', count: counts.hold, name: 'Hold',
        note: 'Gates did not clear. Canary rolled back.' },
      { key: 'unmeasured', count: counts.other, name: 'Unmeasured',
        note: TIMELINE.final_scoreboard.note }
    ];

    d3.select('#scoreboard-tiles').selectAll('div.tile')
      .data(tiles)
      .join('div')
      .attr('class', function (d) { return 'tile ' + d.key; })
      .html(function (d) {
        return '<div class="tile-count">' + d.count + '</div>' +
          '<div class="tile-name">' + d.name + '</div>' +
          '<div class="tile-note">' + d.note + '</div>';
      });

    d3.select('#scoreboard-links').html(
      '<a href="data/decision_cards.json">The gates contract</a>' +
      '<a href="https://github.com/catwang42/agent-topology-decision">This repository</a>' +
      '<a href="https://github.com/catwang42/agent-migration-workbench">The measurement workbench</a>' +
      '<a href="data/status_timeline.json">The rollout timeline</a>'
    );
  }

  // ----------------------------------------------------------------- render

  function visuals(beat) {
    return {
      coldOpen: beat === 0,
      counter: beat === 1,
      trajectory: beat === 1,
      heat: beat >= 3,
      // Beat eight is the scoreboard's alone: the panel would sit behind it,
      // legible through the scrim, saying something the close has moved past.
      panel: beat >= 3 && beat !== 8 && !(state.cardOpen && beat >= 6),
      filters: beat >= 3,
      reasoning: beat >= 4,
      classRings: beat >= 5,
      badges: beat >= 5,
      scrubber: beat >= 7,
      scoreboard: beat === 8,
      free: beat === FREE,
      flow: beat >= 2                      // ambient traffic, continuous from here on
    };
  }

  var revealed = {};   // call sites revealed so far during beat one
  var litEdges = {};

  function render() {
    var beat = state.beat;
    var v = visuals(beat);
    var snapshot = view();

    document.getElementById('coldopen').classList.toggle('on', v.coldOpen);
    document.getElementById('counter').classList.toggle('on', v.counter);
    document.getElementById('filters').classList.toggle('on', v.filters);
    document.getElementById('panel').classList.toggle('on', v.panel);
    document.getElementById('scrubber').classList.toggle('on', v.scrubber);
    document.getElementById('scoreboard').classList.toggle('on', v.scoreboard);
    document.getElementById('card').classList.toggle('on', state.cardOpen && beat >= 6);
    document.getElementById('card').setAttribute('aria-hidden', String(!state.cardOpen));
    document.getElementById('begin-hint').classList.toggle('on', !state.everAdvanced);

    /* Warm means money still sitting there. A call site that has migrated has
       already moved its money, so it goes cool and emerald even though it is
       still one of the larger line items. That colour change is beat seven's
       payoff: the audience should see the heat leave one circle. */
    function warm(d) {
      var row = snapshot.rows[d.id];
      return v.heat && row.hot && row.status !== 'migrated';
    }

    function nodeColor(d) {
      var row = snapshot.rows[d.id];
      if (row.status === 'migrated') return STATUS_COLOR.migrated;
      return HEAT_RAMP(row.heat);
    }

    // Nodes -----------------------------------------------------------------

    /* Which of the four visibility states each call site is wearing. There is
       no fifth state below the floor and no group opacity fading anything
       towards zero: the dimmest a call site ever gets is a state somebody
       chose, and it is still a ring you can read across a room. */
    function tierOf(d) {
      var row = snapshot.rows[d.id];
      if (!v.heat) {
        // Beats zero, one and two. During the trajectory the call sites the
        // run has already touched are lit and the rest hold the neutral
        // state, so what the audience watches is a path through a system
        // rather than a path through the dark.
        if (v.trajectory) return revealed[d.id] ? 'lit' : 'neutral';
        if (v.coldOpen && d.layer === 0) return 'lit';
        return 'neutral';
      }
      if (row.hot) return 'live';
      // Once the rollout starts, anything with a status is part of the story
      // and stays lit even if it has cooled out of the top four.
      if (beat >= 7 && row.status !== 'unmeasured') return 'live';
      // The orchestrator comes back up a step at beat five so its "measure
      // last" badge has a subject. Refusing a verdict is the point of the
      // beat, and a refusal needs something to refuse about.
      if (v.badges && d.behavior_class === 'orchestration') return 'neutral';
      return 'floor';
    }

    nodeSel.attr('opacity', 1)
      .attr('data-tier', tierOf);

    nodeSel.classed('hot', warm);
    nodeSel.classed('migrated', function (d) {
      return v.heat && snapshot.rows[d.id].status === 'migrated';
    });

    nodeSel.select('.node-body')
      .transition().duration(motion.node).ease(d3.easeCubicInOut)
      .attr('fill', function (d) {
        var tier = tierOf(d);
        var row = snapshot.rows[d.id];
        if (tier === 'floor') return FLOOR.fill;
        if (tier === 'neutral') return NEUTRAL.fill;
        if (tier === 'lit') return mix(NEUTRAL.fill, CYAN, 0.24);
        if (row.status === 'migrated') return mix(SURFACE, STATUS_COLOR.migrated, 0.22);
        return mix(SURFACE, nodeColor(d), 0.28);
      })
      .attr('stroke', function (d) {
        var tier = tierOf(d);
        var row = snapshot.rows[d.id];
        if (tier === 'floor') return FLOOR.stroke;
        if (tier === 'neutral') return NEUTRAL.stroke;
        if (tier === 'lit') return CYAN;
        if (row.status === 'migrated') return STATUS_COLOR.migrated;
        return nodeColor(d);
      })
      .attr('stroke-opacity', function (d) {
        var tier = tierOf(d);
        if (tier === 'floor') return FLOOR.strokeOpacity;
        if (tier === 'neutral') return NEUTRAL.strokeOpacity;
        return 1;
      })
      .attr('stroke-width', function (d) {
        var tier = tierOf(d);
        if (tier === 'floor') return FLOOR.strokeWidth;
        if (tier === 'neutral') return NEUTRAL.strokeWidth;
        return 2.4;
      });

    glowSel
      .attr('fill', function (d) {
        if (snapshot.rows[d.id].status === 'hold') return glowGradient(STATUS_COLOR.hold);
        return glowGradient(nodeColor(d));
      })
      .transition().duration(motion.node).ease(d3.easeCubicInOut)
      .attr('r', function (d) {
        var row = snapshot.rows[d.id];
        return warm(d) ? d.r + 16 + row.heat * 26 : 0;
      })
      .attr('opacity', function (d) {
        var row = snapshot.rows[d.id];
        return warm(d) ? 0.4 + row.heat * 0.55 : 0;
      });

    /* The swept ring: how much of the bill this call site is, drawn as how far
       round the circle the arc goes. The hottest is a closed ring. */
    nodeSel.select('.spend-arc')
      .attr('stroke', nodeColor)
      .attr('stroke-dasharray', function (d) {
        var circumference = 2 * Math.PI * (d.r + 4);
        var sweep = circumference * snapshot.rows[d.id].heat;
        return sweep + ' ' + circumference;
      })
      .transition().duration(motion.ring).ease(d3.easeCubicInOut)
      .attr('opacity', function (d) {
        if (!v.heat) return 0;
        return snapshot.rows[d.id].hot ? 0.95 : 0;
      });

    /* The core: the share of billed output tokens that is reasoning the caller
       never sees. Bigger, brighter core means more of what you pay for never
       reaches the customer. */
    function coreRadius(d) {
      return d.r * (0.18 + 0.42 * snapshot.rows[d.id].reasoningShare);
    }

    nodeSel.select('.core')
      .attr('fill', nodeColor)
      .transition().duration(motion.ring).ease(d3.easeCubicInOut)
      .attr('r', function (d) { return v.reasoning && warm(d) ? coreRadius(d) : 0; })
      .attr('opacity', function (d) { return v.reasoning && warm(d) ? 1 : 0; });

    nodeSel.select('.core-bloom')
      .attr('fill', function (d) { return glowGradient(nodeColor(d)); })
      .transition().duration(motion.ring).ease(d3.easeCubicInOut)
      .attr('r', function (d) { return v.reasoning && warm(d) ? coreRadius(d) * 2.4 : 0; })
      .attr('opacity', function (d) { return v.reasoning && warm(d) ? 1 : 0; });

    nodeSel.select('.core-text')
      .text(function (d) { return fmtPct0(snapshot.rows[d.id].reasoningShare); })
      .transition().duration(motion.mark)
      .attr('opacity', function (d) {
        return v.reasoning && warm(d) && coreRadius(d) >= 11 ? 1 : 0;
      });

    nodeSel.select('.class-ring')
      .attr('stroke', function (d) {
        var row = snapshot.rows[d.id];
        if (row.status === 'migrated') return STATUS_COLOR.migrated;
        // A cold class ring still has to be readable — the behaviour class of
        // the fifteen quiet call sites is half of what beat five is saying.
        return row.hot ? nodeColor(d) : '#8496AC';
      })
      .attr('stroke-width', function (d) { return CLASS_STROKE[d.behavior_class].width; })
      .attr('stroke-dasharray', function (d) { return CLASS_STROKE[d.behavior_class].dash; })
      .transition().duration(motion.mark)
      .attr('opacity', v.classRings ? 0.9 : 0);

    nodeSel.select('.node-badge')
      .attr('fill', function (d) {
        return d.behavior_class === 'orchestration' ? '#94A3B8' : CYAN;
      })
      .text(function (d) {
        if (d.behavior_class === 'orchestration') return 'measure last';
        if (d.behavior_class === 'retrieval') return 'trajectory instrument';
        return 'measurable now';
      })
      .transition().duration(motion.mark)
      .attr('opacity', function (d) {
        if (!v.badges) return 0;
        return snapshot.rows[d.id].hot || d.behavior_class === 'orchestration' ? 0.95 : 0;
      });

    nodeSel.select('.status-dot')
      .attr('fill', function (d) { return STATUS_COLOR[snapshot.rows[d.id].status]; })
      .transition().duration(motion.mark)
      .attr('opacity', function (d) {
        if (beat < 7) return 0;
        return snapshot.rows[d.id].status === 'unmeasured' ? 0 : 1;
      });

    nodeSel.select('.node-label')
      .transition().duration(motion.mark)
      .attr('opacity', function (d) {
        var tier = tierOf(d);
        if (tier === 'floor') return FLOOR.label;
        if (tier === 'neutral') return NEUTRAL.label;
        return 1;
      });

    // Edges -----------------------------------------------------------------
    /* The lines are only a scaffold now; the particles carry the traffic. They
       have a floor of their own, for the same reason the glyphs do — a call
       site with no visible wire into it is a call site the audience reads as
       decoration rather than as part of the system. */
    edgeSel
      .transition().duration(motion.ring).ease(d3.easeCubicInOut)
      .attr('opacity', function (d) {
        if (v.trajectory) return litEdges[d.source.id + '>' + d.target.id] ? 0.72 : EDGE_FLOOR;
        if (!v.heat) return 0.34;
        var live = snapshot.rows[d.source.id].hot && snapshot.rows[d.target.id].hot;
        return live ? 0.46 : EDGE_FLOOR;
      })
      .attr('stroke', function (d) {
        if (!v.heat) {
          return v.trajectory && litEdges[d.source.id + '>' + d.target.id] ? CYAN : EDGE_SLATE;
        }
        var live = snapshot.rows[d.source.id].hot && snapshot.rows[d.target.id].hot;
        return live ? HEAT_RAMP(Math.max(snapshot.rows[d.source.id].heat,
                                         snapshot.rows[d.target.id].heat)) : EDGE_SLATE;
      })
      .style('color', function (d) {
        if (!v.heat) return EDGE_SLATE;
        var live = snapshot.rows[d.source.id].hot && snapshot.rows[d.target.id].hot;
        return live ? CYAN : EDGE_SLATE;
      });

    updateFlow(snapshot, v);

    // Chrome ----------------------------------------------------------------
    if (v.panel) renderPanel(snapshot);
    if (state.cardOpen) renderCard(snapshot);
    if (v.scoreboard) renderScoreboard();
    if (v.scrubber) renderScrubber(snapshot);

    scrubRange.value = String(snapshot.week);

    /* The rollout beat, and only the rollout beat. The scrubber stays live
       after it, but a line saying what this week did belongs to the eight
       presses that walk the weeks. */
    var stepping = state.beat === ROLLOUT_BEAT;
    d3.select('#week-event')
      .classed('on', stepping)
      .html(stepping ? weekEventLine(snapshot.week) : '');

    var beatMeta = BEATS[beat];
    d3.select('#caption-beat').text(beatMeta.tag);
    d3.select('#caption-line').text(beatMeta.line);
    d3.select('#beat-count').text(
      beat === FREE ? 'pan, zoom and hover'
        : beat === ROLLOUT_BEAT
          ? 'beat ' + (beat + 1) + ' of ' + NUMBERED_BEATS +
            ' · week ' + snapshot.week + ' of ' + WEEKS
          : 'beat ' + (beat + 1) + ' of ' + NUMBERED_BEATS);

    renderNavigation();

    d3.select('#footer-provenance').text(
      'synthetic traces · seed ' + GRAPH.meta.seed +
      ' · generated ' + GRAPH.meta.generated_on +
      ' · window ' + GRAPH.meta.window_start + ' to ' + GRAPH.meta.window_end
    );
  }

  function renderScrubber(snapshot) {
    var week = TIMELINE.weeks[snapshot.week - 1];
    d3.select('#scrub-week').text(String(snapshot.week));
    d3.select('#scrub-dates').text(week.start + ' to ' + week.end);

    var perDay = snapshot.totalCost / GRAPH.meta.window_days;
    var basePerDay = snapshot.baselineCost / GRAPH.meta.window_days;
    var delta = basePerDay ? (perDay - basePerDay) / basePerDay : 0;
    var deltaClass = delta < -0.0005 ? 'delta-down' : (delta > 0.0005 ? 'delta-up' : '');
    var arrow = delta < -0.0005 ? '▼ ' : (delta > 0.0005 ? '▲ ' : '');

    /* Week seven to week eight goes the wrong way, because the chunk
       summarizer's canary is withdrawn when its gates do not clear. Against
       week one that still reads as a fall, so say it against last week too —
       otherwise the audience has to hold 18.4 percent in their head to notice
       the number got worse. */
    var stepNote = '';
    if (snapshot.week > 1) {
      var previous = weeklySpendPerDay(snapshot.week - 1);
      if (perDay > previous + 0.5) {
        stepNote = '<div class="delta-up">▲ ' + fmtUsd0(perDay - previous) +
          ' on last week</div>';
      }
    }

    d3.select('#scrub-spend').html(
      'spend <b>' + fmtUsd0(perDay) + '</b> per day ' +
      (deltaClass
        ? '<span class="' + deltaClass + '">' + arrow + fmtPct1(Math.abs(delta)) +
          '</span> against week one'
        : '<span style="color:#4E5A6E">at the week one rate</span>') +
      stepNote
    );
  }

  /* What this rollout week did, in one line, derived from the timeline rather
     than authored a second time beside it — so a change to
     data/status_timeline.json cannot leave the caption contradicting the
     graph. A week where no status moves says what is being watched instead,
     because "nothing happened" is the wrong reading: the instruments are
     running, and that is the week's work. */
  function weekEventLine(week) {
    var changes = [];
    nodes.forEach(function (node) {
      var now = statusOf(node.id, week);
      var before = week > 1 ? statusOf(node.id, week - 1) : 'unmeasured';
      if (now !== before) changes.push({ node: node, from: before, to: now });
    });

    var direction;
    if (week === 1) {
      direction = '<span class="week-flat">the rate everything is compared against</span>';
    } else {
      var spendNow = weeklySpendPerDay(week);
      var spendBefore = weeklySpendPerDay(week - 1);
      if (spendNow < spendBefore - 0.5) {
        direction = '<span class="delta-down">spend ▼ ' +
          fmtUsd0(spendBefore - spendNow) + ' a day</span>';
      } else if (spendNow > spendBefore + 0.5) {
        direction = '<span class="delta-up">spend ▲ ' +
          fmtUsd0(spendNow - spendBefore) + ' a day</span>';
      } else {
        direction = '<span class="week-flat">spend unchanged</span>';
      }
    }

    var body;
    if (changes.length) {
      body = changes.map(function (change) {
        return '<b>' + change.node.label + '</b> ' +
          statusMeta(change.from).label.toLowerCase() + ' → ' +
          '<span style="color:' + STATUS_COLOR[change.to] + '">' +
          statusMeta(change.to).label.toLowerCase() + '</span>';
      }).join('<span class="week-event-sep">·</span>');
    } else {
      var watched = nodes.filter(function (node) {
        return statusOf(node.id, week) !== 'unmeasured';
      });
      body = watched.length
        ? 'no status moves — watching ' + watched.map(function (node) {
            return '<b>' + node.label + '</b> in ' +
              statusMeta(statusOf(node.id, week)).label.toLowerCase();
          }).join(' and ')
        : 'nothing is under an instrument yet — this is the bill before anything moved';
    }

    return '<span class="week-event-week">Week ' + week + ' of ' + WEEKS + '</span>' +
      body + '<span class="week-event-sep">·</span>' + direction;
  }

  /* The daily bill at any rollout week, under the filters currently applied.
     Kept separate from view() so the scrubber can look one week back without
     disturbing the state the rest of the page is rendered from. */
  function weeklySpendPerDay(week) {
    var total = 0;
    nodes.forEach(function (node) {
      var baseCost = 0;
      node.cells.forEach(function (cell) {
        if (state.environment !== 'all' && cell.environment !== state.environment) return;
        if (state.team !== 'all' && cell.team !== state.team) return;
        baseCost += cell.cost_usd;
      });
      total += baseCost * statusMeta(statusOf(node.id, week)).cost_multiplier;
    });
    return total / GRAPH.meta.window_days;
  }

  // ------------------------------------------------------- beat animations

  function typeQuestion() {
    var text = GRAPH.meta.opening_question;
    var target = document.getElementById('typed-text');
    target.textContent = '';
    var index = 0;
    function step() {
      if (state.beat !== 0) return;
      target.textContent = text.slice(0, index);
      index += 1;
      if (index <= text.length) later(step, 46);
      else pulseOrchestrator();
    }
    step();
  }

  function pulseOrchestrator() {
    if (state.beat !== 0) return;
    var orchestrator = nodes.filter(function (n) { return n.layer === 0; })[0];
    if (!orchestrator) return;
    var body = nodeSel.filter(function (d) { return d.id === orchestrator.id; }).select('.node-body');
    /* Brightness, not colour. The call site is already cyan at this beat
       because it is the one the question lands on, so the pulse widens and
       narrows its ring rather than swapping it for another palette. */
    function beat() {
      if (state.beat !== 0) return;
      body.transition().duration(760).ease(d3.easeCubicOut)
        .attr('stroke-width', 4).attr('stroke-opacity', 1)
        .transition().duration(760).ease(d3.easeCubicIn)
        .attr('stroke-width', 2.2).attr('stroke-opacity', 0.75)
        .on('end', function () { later(beat, 120); });
    }
    beat();
  }

  function runTrajectory() {
    var featured = TRAJECTORIES.trajectories.filter(function (t) { return t.featured; })[0]
      || TRAJECTORIES.trajectories[0];
    revealed = {};
    litEdges = {};
    pulses.length = 0;
    var counterValue = document.getElementById('counter-value');
    counterValue.textContent = '0';

    var calls = featured.calls;
    var bySeq = {};
    calls.forEach(function (call) { bySeq[call.seq] = call; });

    function step(index) {
      if (state.beat !== 1) return;
      if (index >= calls.length) return;
      var call = calls[index];
      revealed[call.call_site] = true;
      if (call.parent_seq !== null && bySeq[call.parent_seq]) {
        var parent = bySeq[call.parent_seq].call_site;
        var key = parent + '>' + call.call_site;
        if (edgeKey[key]) {
          litEdges[key] = true;
          firePulse(key);
        }
      }
      counterValue.textContent = String(index + 1);
      paintReveal();
      later(function () { step(index + 1); }, 108);
    }
    step(0);
  }

  /* Beat one fires forty seven times in five seconds. A full render each time
     would restart every transition on the page, so the reveal touches only the
     three things that change: which call sites are lit, which edges are lit,
     and one bright pulse racing down the hop that just happened. */
  function paintReveal() {
    var lit = function (d) { return !!revealed[d.id]; };
    nodeSel.select('.node-body')
      .attr('fill', function (d) {
        return lit(d) ? mix(NEUTRAL.fill, CYAN, 0.24) : NEUTRAL.fill;
      })
      .attr('stroke', function (d) { return lit(d) ? CYAN : NEUTRAL.stroke; })
      .attr('stroke-opacity', function (d) { return lit(d) ? 1 : NEUTRAL.strokeOpacity; })
      .attr('stroke-width', function (d) { return lit(d) ? 2.4 : NEUTRAL.strokeWidth; });
    nodeSel.attr('data-tier', function (d) { return lit(d) ? 'lit' : 'neutral'; });
    nodeSel.select('.node-label')
      .attr('opacity', function (d) { return lit(d) ? 1 : NEUTRAL.label; });
    edgeSel
      .attr('opacity', function (d) {
        return litEdges[d.source.id + '>' + d.target.id] ? 0.72 : EDGE_FLOOR;
      })
      .attr('stroke', function (d) {
        return litEdges[d.source.id + '>' + d.target.id] ? CYAN : EDGE_SLATE;
      });
  }

  function firePulse(key) {
    var link = edgeKey[key];
    if (!link) return;
    pulses.push({ geometry: link.geometry, u: 0, duration: 0.34 });
    if (pulses.length > 12) pulses.shift();
  }

  function completeTrajectory() {
    // Entering beat two from either direction leaves every call site revealed.
    nodes.forEach(function (node) { revealed[node.id] = true; });
    links.forEach(function (link) { litEdges[link.source.id + '>' + link.target.id] = true; });
    document.getElementById('counter-value').textContent =
      String(GRAPH.meta.featured_call_count);
  }

  // ------------------------------------------------------------- navigation

  var dotSel = d3.select('#beat-dots').selectAll('button.beat-dot')
    .data(d3.range(NUMBERED_BEATS))
    .join('button')
    .attr('class', 'beat-dot')
    .attr('type', 'button')
    .attr('title', function (i) { return BEATS[i].tag; })
    .attr('aria-label', function (i) { return BEATS[i].tag; })
    .on('click', function (event, i) { event.stopPropagation(); goTo(i); });

  /* The rollout dot grows into a segmented pill while the deck is inside beat
     seven. Eight presses that do not change the beat have to show up
     somewhere, or the presenter loses their place; here each segment is one
     week, the ones behind are filled, and every segment is clickable. */
  var dotsHost = document.getElementById('beat-dots');
  var weekPill = document.createElement('div');
  weekPill.id = 'week-pill';
  dotsHost.insertBefore(weekPill, dotsHost.children[ROLLOUT_BEAT + 1] || null);

  var weekSegSel = d3.select(weekPill).selectAll('button')
    .data(d3.range(1, WEEKS + 1))
    .join('button')
    .attr('class', 'week-seg')
    .attr('type', 'button')
    .attr('title', function (week) { return 'Rollout week ' + week; })
    .attr('aria-label', function (week) { return 'Rollout week ' + week; })
    .text(function (week) { return week; })
    .on('click', function (event, week) { event.stopPropagation(); goToWeek(week); });

  var explorePill = d3.select('#beat-dots').append('button')
    .attr('class', 'beat-pill')
    .attr('type', 'button')
    .attr('id', 'beat-explore')
    .attr('title', BEATS[FREE].tag)
    .text('Explore')
    .on('click', function (event) { event.stopPropagation(); goTo(FREE); });

  document.getElementById('nav-prev').addEventListener('click', function (event) {
    event.stopPropagation();
    retreat();
  });

  document.getElementById('nav-next').addEventListener('click', function (event) {
    event.stopPropagation();
    advance();
  });

  function renderNavigation() {
    var inRollout = state.beat === ROLLOUT_BEAT;
    dotSel
      .classed('on', function (i) { return i === state.beat && !inRollout; })
      .classed('past', function (i) { return i < state.beat; })
      // The rollout dot is not hidden so much as unrolled: the pill takes its
      // place in the row, at the position it was standing in.
      .classed('folded', function (i) { return inRollout && i === ROLLOUT_BEAT; });
    d3.select(weekPill).classed('on', inRollout);
    weekSegSel
      .classed('on', function (week) { return inRollout && week === state.week; })
      .classed('past', function (week) { return inRollout && week < state.week; });
    explorePill.classed('on', state.beat === FREE);
    document.getElementById('nav-prev').disabled = state.beat === 0;
    document.getElementById('nav-next').disabled = state.beat === FREE;
  }

  /* What the right arrow, the space bar, the forward button and a click on
     the canvas all mean.
     *
     * Beat seven is eight beats wearing one coat. Inside it an advance steps
     * exactly one rollout week and nothing else moves, because the presenter
     * is saying a sentence about each week and a timer that runs ahead of
     * them is a timer they have to apologise for. Only week eight hands the
     * deck on to the close; only week one hands it back to the decision.
     */
  function advance() {
    if (state.beat === ROLLOUT_BEAT && state.week < WEEKS) {
      goToWeek(state.week + 1);
      return;
    }
    goTo(state.beat + 1);
  }

  function retreat() {
    if (state.beat === ROLLOUT_BEAT && state.week > 1) {
      goToWeek(state.week - 1);
      return;
    }
    goTo(state.beat - 1);
  }

  /* One week of the rollout. Stepping a week is a smaller move than changing
     beat, so it gets the shorter transition and it does not disturb the beat's
     furniture. Arriving at the rollout from somewhere else is a beat change
     first — otherwise clicking a week from the scoreboard would leave the
     decision card down, and the rollout is that card's story. */
  function goToWeek(week) {
    if (state.beat !== ROLLOUT_BEAT) goTo(ROLLOUT_BEAT);
    state.week = Math.max(1, Math.min(WEEKS, week));
    state.everAdvanced = true;
    clearTimers();
    motion = WEEK_MOTION;
    render();
    motion = BEAT_MOTION;
  }

  function goTo(beat) {
    beat = Math.max(0, Math.min(FREE, beat));
    motion = BEAT_MOTION;
    var previous = state.beat;
    if (beat !== 0) state.everAdvanced = true;
    clearTimers();
    pulses.length = 0;
    state.beat = beat;

    /* The rollout is entered at its first week going forwards and at its
       last week coming back, so stepping into beat seven from either side
       lands on the week the presenter just left. */
    if (beat < ROLLOUT_BEAT) state.week = 1;
    if (beat === ROLLOUT_BEAT) state.week = previous > ROLLOUT_BEAT ? WEEKS : 1;
    if (beat > ROLLOUT_BEAT) state.week = WEEKS;

    // The decision card opens on the hottest call site at beat six and stays
    // open through the rollout, because the rollout is that card's story. Beat
    // eight takes it back down: the scoreboard is the closing image and should
    // not have to share the canvas with anything.
    if (beat >= 6 && beat !== 8) {
      if (!state.selected) {
        state.selected = view().ranked[0].id;
        state.cardOpen = true;
      }
    } else {
      state.cardOpen = false;
      state.selected = null;
    }

    if (beat === 0) {
      revealed = {};
      litEdges = {};
      typeQuestion();
    } else if (beat === 1) {
      runTrajectory();
    } else if (beat >= 2) {
      completeTrajectory();
    }

    // Fade the caption line so a beat change reads as a change.
    var caption = document.getElementById('caption');
    caption.classList.add('swap');
    later(function () { caption.classList.remove('swap'); }, 60);

    updateZoomAvailability();
    render();
    fitCamera(true);
  }

  window.addEventListener('keydown', function (event) {
    if (event.key === 'ArrowRight' || event.key === ' ' || event.key === 'PageDown') {
      event.preventDefault();
      advance();
    } else if (event.key === 'ArrowLeft' || event.key === 'PageUp') {
      event.preventDefault();
      retreat();
    } else if (event.key === 'Escape') {
      state.cardOpen = false;
      render();
      fitCamera(true);
    } else if (event.key === 'Home') {
      goTo(0);
    }
  });

  /* Clicking the canvas advances. Anything that is itself a control keeps its
     own click, and every one of those controls looks like a control — there
     are no invisible hotspots left on this page. */
  var INTERACTIVE = '#controls, #filters, #card, #panel, #scrubber, #scoreboard-links, ' +
                    '.node-hit, a, button, input';

  document.getElementById('stage').addEventListener('click', function (event) {
    if (event.target.closest && event.target.closest(INTERACTIVE)) return;
    advance();
  });

  // --------------------------------------------------------- free explore

  /* The extent is stated rather than inferred. The canvas band is the frame the
     audience is looking at, so that is what a pan is measured against — and
     saying so keeps the zoom off the document's own idea of the viewport. */
  var zoom = d3.zoom()
    .extent([[0, 0], [CANVAS_W, CANVAS_H]])
    .scaleExtent([0.4, 3.4])
    .on('zoom', function (event) { applyCamera(event.transform); });

  // Pan and zoom belong to free explore only. During the beats the camera is
  // the presenter's, not the audience's.
  function updateZoomAvailability() {
    if (state.beat === FREE) {
      svg.call(zoom).on('dblclick.zoom', null);
      svg.call(zoom.transform,
        d3.zoomIdentity.translate(camera.x, camera.y).scale(camera.k));
    } else {
      svg.on('.zoom', null);
    }
  }

  // ------------------------------------------------------------------ scale

  function fitStage() {
    var scale = Math.min(window.innerWidth / 1440, window.innerHeight / 900);
    stageScale = Math.min(1, scale);
    var left = Math.max(0, (window.innerWidth - CANVAS_W * stageScale) / 2);
    var top = Math.max(0, (window.innerHeight - 900 * stageScale) / 2);
    document.getElementById('stage').style.transform =
      'translate(' + left + 'px,' + top + 'px) scale(' + stageScale + ')';
  }

  window.addEventListener('resize', fitStage);
  fitStage();

  goTo(0);
}());
